import type { ModulePageConfig } from '../../types/module'
import {
  Activity,
  AlertTriangle,
  BarChart3,
  Bell,
  Boxes,
  Calendar,
  CheckCircle2,
  Coins,
  Copy,
  DollarSign,
  FileText,
  Filter,
  Layers,
  LayoutDashboard,
  Megaphone,
  MousePointerClick,
  Package,
  PauseCircle,
  Target,
  TrendingDown,
  TrendingUp,
  Truck,
  Wallet,
} from 'lucide-react'

export const adsModuleConfig: ModulePageConfig = {
  layout: 'modern',
  theme: {
    rgba: 'rgba(236,72,153,',
    hex: '#ec4899',
    dim: 'rgba(236,72,153,0.12)',
    dark: '#db2777',
    glow: '0 0 28px rgba(236,72,153,0.40)',
    linkHoverClass: 'hover:text-fuchsia-400',
    relatedHoverBorderClass: 'hover:border-fuchsia-500/40',
    relatedHoverTextClass: 'group-hover:text-fuchsia-400',
  },
  back: {
    label: 'العودة إلى جميع الوحدات',
    linkToFeatures: true,
  },
  hero: {
    badgeIcon: Megaphone,
    badgeLabel: 'الحملات الإعلانية والتحليلات',
    title: <>اعرف أي حملة <span style={{ color: '#ec4899' }}>تُربحك — وأيها تُحرق أموالك.</span><br />ROAS. CPA. <span className="text-ocean-400">تنبيه MaxCPO تلقائي.</span></>,
    description: '٦ مؤشرات أداء إعلاني — مستمدة من طلباتك الحقيقية المرتبطة بكل حملة على Facebook وGoogle وTikTok وSnapchat. تحليل يومي وشهري. تنبيهات CPO تلقائية. لا تخمين — قرارات مبنية على بيانات.',
    microStatsPills: [
      { icon: TrendingUp, label: 'ROAS من طلباتك الحقيقية' },
      { icon: Bell, label: 'تنبيه MaxCPO تلقائي' },
      { icon: BarChart3, label: 'يومي وشهري تلقائياً' },
    ],
    primaryCtaLabel: 'ابدأ الآن مجاناً',
    secondaryCtaLabel: 'اكتشف كل الوحدات',
    secondaryCtaToFeatures: true,
    image: {
    src: './assets/ads-1-hero.png',
    alt: 'لوحة تحليلات الإعلانات — ROAS وCPA وأداء الحملات',
    width: 780,
    height: 480,
    loading: 'eager',
  },
    imageAnimation: 'modern',
  },
  pain: {
    stats: [
      { icon: AlertTriangle, value: '٦٠٪', label: 'من أصحاب المتاجر لا يعرفون ROAS حملاتهم الحقيقي — لأنهم يقيسون "نقرات" لا طلبات مُسلَّمة داخل النظام. الفرق بين الرقمين يمكن أن يقلب قرار الصرف رأساً على عقب.' },
      { icon: Copy, value: 'يومياً', label: 'تدخل أرقاماً إعلانية يدوياً في إكسيل لأن منصتك لا تربط الإنفاق بالطلبات. هنا: أدخل الإنفاق مرة — النظام يحسب ROAS وCPA وCPI من طلباتك الفعلية تلقائياً.' },
      { icon: TrendingDown, value: '٣x', label: 'متوسط تضخم ROAS المُعلَن من المنصات الإعلانية مقارنةً بالواقع — لأنها تحتسب كل نقرة وزيارة. هنا ROAS = إيراد الطلبات المرتبطة ÷ الإنفاق الفعلي — ببيانات متجرك أنت.' },
    ],
  },
  value: {
    sectionLabel: 'لماذا إدارة الإعلانات؟',
    title: 'لأن كل جنيه إعلاني يستحق أن يُقاس بدقة.',
    subtitle: 'ربط بيانات الإنفاق الإعلاني بطلبات متجرك الحقيقية — هكذا تعرف من أي حملة جاء كل طلب، ما تكلفته، وما نسبة تسليمه. قرارات تسويقية مبنية على واقع — لا على وهم المنصة.',
    cards: [
      { icon: TrendingUp, title: 'ROAS حقيقي من طلباتك — لا من النقرات', desc: 'ROAS = Revenue ÷ Spend. Revenue مأخوذ من Orders + ArchivedOrders المرتبطة بكل حملة عبر CampaignId — بعد استبعاد الملغى. ليس إحصاء المنصة الإعلانية — هذا رقم صندوقك الفعلي.', color: '' },
      { icon: Bell, title: 'تنبيه MaxCPO — إنذار قبل أن تخسر', desc: 'حدِّد MaxCPO لكل حملة (الحد الأقصى المسموح لتكلفة الطلب). عند كل إدخال إنفاق: النظام يحسب CPA = TotalSpend ÷ Orders — لو تجاوز MaxCPO يُنشئ SystemAlert تلقائياً. تنبيه واحد يومياً لكل حملة لتجنب الإزعاج.', color: '' },
      { icon: MousePointerClick, title: 'CPA وCPI — تكلفة الطلب والمنتج', desc: 'CPA = Spend ÷ Orders (تكلفة الحصول على طلب). CPI = Spend ÷ Items (تكلفة الحصول على قطعة واحدة). Items يُحسَب من OrderItems.Quantity — UNION ALL على live + archived في استعلام واحد. قرِّر بمستوى القطعة لا الطلب.', color: '' },
      { icon: Activity, title: 'Campaign Delivery Rate — نسبة التسليم الحقيقية', desc: 'Delivered + PartiallyDelivered من إجمالي طلبات الحملة × ١٠٠. اعرف أي حملة تجلب عملاء يستلمون — وأيها تجلب "مرتجعات". سلاح أسراري لتحسين الاستهداف.', color: '' },
      { icon: BarChart3, title: 'مخططات يومية/شهرية تلقائية', desc: 'الفترة ≤ ٣٠ يوماً؟ عرض يومي. أكثر من ٣٠ يوماً؟ تجميع شهري في PostgreSQL (TO_CHAR/GROUP BY) — لا materialization للصفوف قبل التجميع. Bar chart أو Line chart بزر واحد.', color: '' },
      { icon: Layers, title: 'Platform Breakdown — Facebook vs TikTok vs Google', desc: 'الإنفاق والإيراد والطلبات وROAS وCPA لكل منصة مستقلةً. المنصات مصدرها نفس الطلبات المرتبطة. اعرف أين يُدر إنفاقك أعلى عائد — وانقل ميزانيتك بثقة.', color: '' },
      { icon: Target, title: 'Budget Exceeded — رادار ميزانية الحملة', desc: 'كل حملة لها Budget محدَّد. عند كل حفظ إنفاق يومي: يُقارَن TotalSpend بالـ Budget — إذا تجاوز يظهر تحذير أحمر على الحملة فوراً. لا تصحَّ ميزانية بعد انتهاء الحملة.', color: '' },
      { icon: Copy, title: 'Copy Previous Day — ادخال سريع بنقرة', desc: 'يوم الإنفاق مكرَّر من أمس؟ اضغط "Copy Previous Day" — النظام يجلب إنفاق أمس ويملأ بيانات اليوم تلقائياً لنفس الحملات. يُعرَض رسالة إن لم توجد بيانات سابقة بدلاً من صمت.', color: '' },
      { icon: Coins, title: 'Ad Charge كمصروف محمي', desc: 'سجِّل شحن منصة إعلانية (Top-up) كمصروف محمي — يُحفَظ في جدول المصروفات بتصنيف Ads وعلامة is_auto=1. لا يمكن تعديله لاحقاً. التكلفة تظهر في Burn Rate ضمن التقارير المالية.', color: '' },
      { icon: Filter, title: 'فلترة متعددة المحاور في ثانية', desc: 'فلتر بالتاريخ + المنصة + اسم الحملة — يعمل على كل الجداول والمخططات في آنٍ واحد. البحث يُقيَّد بـ ١٠٠ حرف ونطاق ٣٦٦ يوماً لحماية أداء قاعدة البيانات.', color: '' },
      { icon: PauseCircle, title: 'إيقاف/تشغيل الحملة بمفتاح واحد', desc: 'كل حملة لها Status: Active أو Paused. الحملات المتوقفة لا تظهر في شاشة الإدخال اليومي. التبديل فوري — UpdateAsync بدون إعادة تحميل الصفحة. EndDate تُضبَط تلقائياً عند الإيقاف.', color: '' },
      { icon: Calendar, title: 'Timeline Analytics — منحنى ROAS وCPA يومياً', desc: 'Endpoint مستقل للجدول الزمني: per-day Spend + Revenue + ROAS + CPA للمقارنة بين أيام الأسبوع. اكتشف بأي يوم إنفاقك أكثر كفاءة — وانظم إطلاق حملاتك بناءً عليه.', color: '' },
    ],
  },
  walkthrough: {
    sectionLabel: 'كيف يعمل؟',
    title: 'من إنفاق إعلاني إلى قرار تسويقي مبني على بيانات',
    subtitle: '',
    tabs: [
      {
        id: 'campaigns',
        label: 'إدارة الحملات',
        icon: Megaphone,
        imgSrc: './assets/ads-2-list.png',
        imgAlt: 'إدارة الحملات — جدول الحملات مع Budget وMaxCPO والحالة',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: 'أضف حملتك: منصة، ميزانية، MaxCPO', desc: 'اسم الحملة + المنصة (Facebook/Google/TikTok/Snapchat) + الميزانية الكلية. الجديد: MaxCPO — حدِّد الحد الأقصى لتكلفة الطلب. عند تجاوزه: SystemAlert تُنشأ تلقائياً— بشرط: لا يوجد تنبيه آخر غير مقروء لنفس الحملة اليوم.' },
          { title: 'تفعيل/إيقاف بمفتاح واحد', desc: 'كل حملة لها Status Switch. OFF = Paused → تُضبَط EndDate تلقائياً ولا تظهر في الإدخال اليومي. ON = Active → تُمسَح EndDate وتعود للعمل. الحملات المتوقفة لا تُلوِّث تحليلاتك بإنفاق صفري.' },
          { title: 'حماية البيانات عند الحذف', desc: 'Soft Delete: الحملات المرتبطة بطلبات أو إنفاق لا تُحذَف — يُرفَض الطلب مع رسالة واضحة. حملات بدون بيانات تُحذَف بعلامة IsDeleted + DeletedAt + Timestamp — لا حذف فعلي من قاعدة البيانات.' },
          { title: 'ربط الحملة بالطلبات عبر CampaignId', desc: 'كل طلب يحمل CampaignId المرتبط بحملة. الطلبات الحية والمؤرشفة تُحتسَب معاً في التحليلات. في حالة وجود نفس الطلب في المصدرين: الطلب الحي يأخذ الأولوية (Dictionary deduplication — Live wins).' },
        ],
      },
      {
        id: 'spend',
        label: 'إدخال الإنفاق اليومي',
        icon: DollarSign,
        imgSrc: './assets/ads-3-action.png',
        imgAlt: 'إدخال الإنفاق اليومي — مصفوفة الحملات مع Copy Previous Day',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: 'مصفوفة الإنفاق: كل حملة في سطر', desc: 'اختر التاريخ — يظهر سطر لكل حملة Active فقط. أدخل الإنفاق لكل حملة. القيم السالبة تُعامَل كـ ٠. القيم الصفرية مع وجود سجل قديم تُحدَّث. القيم الصفرية بدون سجل لا تُدرَج — لا إدخالات وهمية.' },
          { title: 'Copy Previous Day — إنتاجية عالية', desc: 'اضغط "Copy Previous Day" فيملأ النظام إنفاق أمس لنفس الحملات. إن لم تكن هناك بيانات أمس أو كانت كلها أصفاراً: "No previous day data" — رسالة واضحة بدلاً من صمت محبط.' },
          { title: 'Ad Charge — شحن منصة كمصروف محمي', desc: 'سجِّل شحن حساب إعلاني (Facebook Ads Top-up مثلاً): اختر المنصة، أدخل المبلغ والتاريخ. يُحفَظ كمصروف في جدول Expenses بتصنيف Ads وعلامة is_auto=1 — لا يمكن تعديله لاحقاً. يظهر في Burn Rate بالتقارير المالية.' },
          { title: 'تحقق من الميزانية عند كل حفظ', desc: 'بعد حفظ الإنفاق: النظام يحسب TotalSpend لكل حملة ويُقارن بـ Budget. عند التجاوز: تحذير أحمر على صف الحملة. التحقق من MaxCPO يعمل بالتزامن: CPA = TotalSpend ÷ Orders — إن تجاوز الحد يُنبِّه.' },
        ],
      },
      {
        id: 'analytics',
        label: 'التحليلات والـ ROAS',
        icon: BarChart3,
        imgSrc: './assets/ads-4-details.png',
        imgAlt: 'التحليلات والـ ROAS — KPIs ومخططات تكيفية وجدول أداء الحملات',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: '٦ KPIs مرتبطة بطلباتك الحقيقية', desc: 'Total Spend، Revenue (OrderPrice أو TotalAmount fallback)، ROAS، CPA، CPI، Campaign Delivery Rate — كلها مشتقة من الطلبات المرتبطة بـ CampaignId في الفترة المحددة. الطلبات الملغاة مستبعدة. Archived Orders تُعدُّ كالحية.' },
          { title: 'Platform Breakdown — قارن Facebook بـ TikTok', desc: 'جدول المنصات: Spend، Orders، Revenue، ROAS، CPA لكل منصة. ROAS أخضر عند ≥٢ وأحمر دون ذلك — نظرة واحدة تكفي. تصفية بالمنصة تُطبَّق على الجداول والمخططات معاً.' },
          { title: 'مخططات تكيَّفية: يومي أو شهري', desc: 'نطاق ≤ ٣٠ يوماً: بيانات يومية. نطاق > ٣٠ يوماً: تجميع شهري في PostgreSQL (GROUP BY Year*100+Month). أربعة مخططات: Spend، Revenue، ROAS، CPA — يمكن عرضها كبار أو خطوط. لا حاجة لإعادة تحميل عند التبديل.' },
          { title: 'Campaign Performance Table — قرار بنقرة', desc: 'جدول لكل حملة بجميع KPIs: Spend، Revenue، Orders، Items، ROAS، CPA، CPI، Delivery Rate. مرتَّب تنازلياً بالإنفاق. اضغط على أي عمود للفرز. فلترة بالمنصة والاسم تعمل فورياً. حملات بدون إنفاق وإيراد مستبعدة من الجدول.' },
        ],
      },
      {
        id: 'alerts',
        label: 'التنبيهات والتصدير',
        icon: Bell,
        imgSrc: './assets/ads-5-extras.png',
        imgAlt: 'تنبيهات MaxCPO وBudget Warning وTimeline Analytics وتصدير PDF',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: 'MaxCPO Alert — نظام إنذار CPA ذكي', desc: 'لكل حملة MaxCPO: النظام يحسب CPA = Total Spend ÷ (Live Orders + Archived Orders). إذا CPA > MaxCPO: يُنشئ SystemAlert من نوع Warning برسالة صريحة مثل: "CPA (٤٥.٢) تجاوز MaxCPO (٣٠) لحملة \\\'Ramadan Campaign\\\'". فلتر مانع للتكرار اليومي.' },
          { title: 'Budget Warning — لا تتجاوز بدون علم', desc: 'عند كل حفظ إنفاق يومي: يُحسَب TotalSpend من DailyAdSpends بـ GroupBy + SumAsync في PostgreSQL — لا تحميل صفوف للمقارنة. كل حملة تجاوزت ميزانيتها تظهر في رسالة التحذير مجمَّعةً: "Campaigns X، Y تجاوزت ميزانياتها".' },
          { title: 'Timeline Analytics — منحنى كفاءتك الإعلانية', desc: 'Endpoint مستقل /analytics/timeline: per-day ROAS وCPA وRevenue وSpend في نطاق زمني مخصَّص. مثالي للمقارنة: هل كفاءتي الإعلانية تحسَّنت بعد تغيير الإبداعات؟ هل يوم السبت أفضل من الإثنين؟' },
          { title: 'PDF Export — تقرير جاهز للعرض', desc: 'يُولِّد تقرير PDF من التحليلات الحالية (مع الفلاتر المطبَّقة): KPIs، Platform Breakdown، Campaign Performance Table — باسم الشركة وتاريخ التوليد. مناسب للعرض على العميل أو مدير التسويق.' },
        ],
      },
    ],
  },
  faq: {
    title: <>ROAS حقيقي — <span style={{ color: '#ec4899' }}>يأتي من طلباتك أنت.</span></>,
    subtitle: '',
    items: [
      { q: 'كيف يُحسَب ROAS من طلبات متجري لا من بيانات المنصة؟', a: 'كل طلب يحمل CampaignId. عند تحليل الإعلانات: يُجلَب كل طلب (حي + مؤرشَف) مرتبط بحملة في نطاق التاريخ، مستبعداً الملغى. Revenue = OrderPrice (أو TotalAmount كـ fallback). ROAS = SUM(Revenue) ÷ TotalSpend. لو كان بعض الطلبات في الأرشيف والآخر حي لنفس الطلب — الحي يأخذ الأولوية تجنباً للعد المزدوج.' },
      { q: 'ما هو MaxCPO ومتى يُرسَل التنبيه؟', a: 'MaxCPO هو الحد الأقصى لتكلفة الطلب (Cost Per Order) الذي تقبله لحملة معينة. عند كل حفظ إنفاق يومي: النظام يحسب CPA = TotalSpend ÷ (Live Orders + Archived Orders). إذا CPA > MaxCPO: يُنشئ SystemAlert من نوع Warning. شرط: لا يوجد تنبيه غير مقروء لنفس الحملة اليوم — يمنع التنبيهات المتكررة التي تُزعج.' },
      { q: 'لماذا تظهر الحملات المتوقفة في التحليلات لكن لا في الإدخال اليومي؟', a: 'الإدخال اليومي يُظهر الحملات النشطة فقط (Status = Active) — منطقي لأنك لا تنفق على حملات متوقفة. التحليلات تُظهر كل الحملات للفترة المحددة لأن بيانات الإنفاق والطلبات التاريخية موجودة. يمكنك فلترة بمنصة أو اسم لتضييق النتائج.' },
      { q: 'هل يؤثر نطاق التاريخ على طريقة عرض المخططات؟', a: 'نعم — تلقائياً: نطاق ≤ ٣٠ يوماً → عرض يومي (GROUP BY Date). نطاق > ٣٠ يوماً → تجميع شهري في PostgreSQL (GROUP BY Year*100+Month). كلا الوضعين يحسبان Spend وRevenue وROAS وCPA في SQL — لا materialization للصفوف للتجميع. البار وال Line chart متاحان في كلا الوضعين.' },
      { q: 'ما الفرق بين "New Charge" وإدخال الإنفاق اليومي؟', a: 'Daily Spend: يسجِّل إنفاقك الإعلاني الفعلي على كل حملة يومياً — يُستخدَم في حساب ROAS وCPA. New Charge: يسجِّل شحن حسابك الإعلاني على المنصة (Top-up) كمصروف في جدول Expenses بتصنيف Ads — يُؤثِّر على Burn Rate في التقارير المالية ولا يمكن تعديله. الأول قابل للتحديث؛ الثاني محمي.' },
      { q: 'كيف يُحسَب CPI (Cost Per Item)؟', a: 'CPI = TotalSpend ÷ TotalItems. TotalItems = SUM(OrderItems.Quantity) لكل الطلبات المرتبطة بالحملة. يُستخدَم UNION ALL على live OrderItems + archived OrderItems في استعلام واحد لتجنب round-trips. لو حملة تبيع منتجات متعددة لكل طلب — CPI يعطيك التكلفة الحقيقية بمستوى القطعة.' },
      { q: 'ما الحد الأقصى لنطاق التاريخ في التحليلات؟', a: '٣٦٦ يوماً (سنة كاملة). هذا القيد مفروض server-side في Controller قبل أي معالجة — يحمي أداء قاعدة البيانات من استعلامات ثقيلة. عنصر البحث النصي محدود بـ ١٠٠ حرف. كلا القيدين يُعيدان BadRequest مع رسالة واضحة.' },
      { q: 'هل يمكن تتبع حملة على أكثر من منصة؟', a: 'كل حملة مرتبطة بمنصة واحدة. لتتبع نفس الإعلان على فيسبوك وتيك توك: أنشئ حملتين منفصلتين بنفس الاسم لكل منصة — Platform Breakdown يُقارن بينهما مباشرةً في لوحة التحليلات.' },
    ],
  },
  related: {
    layout: 'modern',
    title: <>الإعلانات <span style={{ color: '#ec4899' }}>تُغذِّي كل القرارات المالية والتشغيلية</span></>,
    items: [
      { to: '/features/reports', icon: FileText, title: 'التقارير المالية', body: 'Ad Charges تظهر في Burn Rate وTotal Expenses في التقارير. Campaign ROAS وCPO يُكمِّلان تقرير الـ Financial Settlement.' },
      { to: '/features/dashboard', icon: LayoutDashboard, title: 'لوحة القيادة', body: 'Campaign Performance مخطط في لوحة القيادة يسحب نفس بيانات ROAS وCPO مباشرةً — رؤية سريعة بدون الدخول للوحدة.' },
      { to: '/features/expenses', icon: Wallet, title: 'المصروفات والخزينة', body: 'Ad Charges المسجَّلة كـ New Charge تظهر في المصروفات تلقائياً بتصنيف Ads is_auto=1. تؤثر على الخزينة ورصيدها مباشرةً.' },
      { to: '/features/shipping', icon: Truck, title: 'الشحن', body: 'Campaign Delivery Rate مشتق من حالات الشحن (Delivered + PartiallyDelivered). تحسين معدل التسليم يُحسِّن هذا المقياس مباشرةً.' },
      { to: '/features/inventory', icon: Boxes, title: 'المخزون', body: 'CPI (تكلفة القطعة الإعلانية) مرتبط بعدد OrderItems. ربط تكلفة المنتج بتكلفة اكتسابه من الإعلانات يكشف الهامش الحقيقي.' },
      { to: '/features/preparation', icon: Package, title: 'التحضير', body: 'الطلبات القادمة من حملات ذات ROAS عالٍ لها أولوية في التحضير — التكامل بين الإعلانات والتوزيع يُعظِّم سرعة التسليم.' },
    ],
  },
  cta: {
    layout: 'modern',
    icon: Megaphone,
    eyebrow: 'ابدأ الآن',
    title: <>هل تعرف أي حملتك <span style={{ color: '#ec4899' }}>تُربحك اليوم؟</span></>,
    description: 'لا تكتفِ بأرقام المنصة — اربط إنفاقك الإعلاني بطلباتك الحقيقية. اعرف ROAS كل حملة، تكلفة كل طلب، ونسبة تسليمه — كلها من نفس النظام الذي تُدير فيه متجرك.',
    primaryLabel: 'ابدأ الآن مجاناً',
    secondaryLabel: 'استعرض الوحدات',
    secondaryToFeatures: true,
    trustBadges: [
      { icon: CheckCircle2, text: 'بدون بطاقة ائتمانية' },
      { icon: CheckCircle2, text: 'إعداد في أقل من ٥ دقائق' },
      { icon: CheckCircle2, text: 'دعم فني كامل بالعربية' },
    ],
  },
}
