import type { ModulePageConfig } from '../../types/module'
import {
  Activity,
  AlertTriangle,
  BarChart2,
  BarChart3,
  Boxes,
  CheckCircle2,
  Clock,
  Coins,
  Landmark,
  Layers,
  LayoutDashboard,
  Map,
  Megaphone,
  Package,
  ShieldCheck,
  Star,
  Target,
  TrendingDown,
  TrendingUp,
  Truck,
  Users,
  Wallet,
  Zap,
} from 'lucide-react'

export const dashboardModuleConfig: ModulePageConfig = {
  layout: 'modern',
  theme: {
    rgba: 'rgba(244,63,94,',
    hex: '#f43f5e',
    dim: 'rgba(244,63,94,0.12)',
    dark: '#e11d48',
    glow: '0 0 28px rgba(244,63,94,0.40)',
    linkHoverClass: 'hover:text-rose-400',
    relatedHoverBorderClass: 'hover:border-rose-500/40',
    relatedHoverTextClass: 'group-hover:text-rose-400',
  },
  back: {
    label: 'العودة إلى جميع الوحدات',
    linkToFeatures: true,
  },
  hero: {
    badgeIcon: LayoutDashboard,
    badgeLabel: 'لوحة القيادة التنفيذية',
    title: <>كل أرقامك — <span style={{ color: '#f43f5e' }}>في شاشة واحدة.</span><br />إيراد، ربح، نمو، <span className="text-ocean-400">لحظياً.</span></>,
    description: 'أكثر من ٢٠ مخطط وتحليل.. هتعرف مبيعاتك جاية منين بالظبط، وصافي ربحك كام بعد كل المصاريف. كل الأرقام قدامك حقيقية ومتحدثة لحظة بلحظة， عشان تاخد قرارك وأنت مطمن وتكبر شغلك على نور.',
    microStatsPills: [
      { icon: Coins, label: 'ربح حقيقي لا إيراد فقط' },
      { icon: TrendingUp, label: 'نمو % مقارنةً بالفترة السابقة' },
      { icon: Zap, label: 'كاش ١٠ دقائق + تحديث فوري' },
    ],
    primaryCtaLabel: 'ابدأ الآن مجاناً',
    secondaryCtaLabel: 'اكتشف كل الوحدات',
    secondaryCtaToFeatures: true,
    image: {
    src: './assets/dsh-1-hero.png',
    alt: 'لوحة القيادة التنفيذية — KPIs والمخططات',
    width: 780,
    height: 480,
    loading: 'eager',
  },
    imageAnimation: 'modern',
  },
  pain: {
    stats: [
      { icon: AlertTriangle, value: '٧١٪', label: 'من أصحاب المتاجر الإلكترونية لا يعرفون ربحيتهم الفعلية — يرون الإيراد ويفرحون، لكن يغفلون عن تكلفة البضاعة.' },
      { icon: Clock, value: '٣ ساعة', label: 'متوسط الوقت الذي يقضيه المدير أسبوعياً في جمع الأرقام من إكسيل ومنصات الشحن يدوياً — وقت يمكن أن ينقذه نظام واحد.' },
      { icon: TrendingDown, value: '٤٨٪', label: 'من قرارات التسويق تُبنى على حدس لا بيانات — ربط الإنتاج بنسبة ROAS والطلبات بحملة بعينها يُغير كل شيء.' },
    ],
  },
  value: {
    sectionLabel: 'لماذا لوحة القيادة؟',
    title: 'أكثر من ٢٠ تحليل — كلها في ثانية واحدة.',
    subtitle: 'لوحة القيادة ليست مجرد أرقام — هي قرارات. كل مؤشر مصمَّم ليجيب على سؤال تجاري حقيقي: أين أربح؟ أين أخسر؟ ومن أكبر عملائي؟',
    cards: [
      { icon: Coins, title: 'ربح حقيقي — لا إيراد وهمي', desc: 'رسم بياني واحد بيعرفك حركة مبيعاتك وماشية إزاي، وبيحط لك البيع جنبه المكسب عشان الصورة توضح. الحسبة هنا بالمليم: بنخصم تكلفة البضاعة اللي اتسلمت فعلياً من إجمالي الفلوس اللي دخلتلك، عشان تعرف "الصافي" في جيبك كام.. وتطمن إنك بتكسب مش بتبيع بخسارة.', color: '' },
      { icon: TrendingUp, title: 'نمو % مقارنةً بفترة مطابقة سابقة', desc: 'نسبة النمو محسوبة تلقائياً بمقارنة الفترة المختارة بالفترة السابقة المطابقة في المدة. مثال: اخترت آخر ٧ أيام → يقارن بالـ٧ أيام التي قبلها. النتيجة: RevenueGrowthPct و OrderCountGrowthPct بدقة عشرية.', color: '' },
      { icon: Zap, title: 'كاش ذكي بإبطال فوري', desc: 'KPIs تُكاش لـ١٠ دقائق. Charts تُكاش بنفس المدة. كلاهما مرتبط بـ CancellationChangeToken لكل مستأجر — عند أي تغيير في البيانات يُلغى الكاش فوراً بدون انتظار انتهاء المدة. السرعة والدقة معاً.', color: '' },
      { icon: Activity, title: 'Sidebar KPIs حية بمعدل ٣٠ ثانية', desc: 'الـ Sidebar يعرض ٦ مؤشرات: طلبات التحضير، الشحن المتأخر، تنبيهات المخزون، الديون المتأخرة، طلبات اليوم — تُكاش ٣٠ ثانية. رصيد الخزينة يُجلَب حياً في كل طلب لضمان الدقة الفورية.', color: '' },
      { icon: Layers, title: 'Orders + ArchivedOrders في كل استعلام', desc: 'كل أرقامك وتقاريرك بتجمع بين الأوردرات الحالية واللي اتأرشفت مع بعض.. مفيش أوردر بيقع من الحسابات حتى بعد ما يتأرشف. هتشوف تاريخ شغلك كله من أول يوم لحد دلوقتي كامل ومن غير أي نقص.', color: '' },
      { icon: ShieldCheck, title: 'عزل بيانات متعدد الطبقات', desc: 'بياناتك متأمنة بفلترين فوق بعض؛ السيستم متبرمج يقفل أي ثغرة ومستحيل شركة تشوف بيانات شركة تانية، حتى لو حصل غلط في فلتر منهم التاني بيفضل حارس للداتا بتاعتك.. أمان كامل لبياناتك ومستحيل تتداخل مع غيرك.', color: '' },
      { icon: Map, title: 'مبيعات ومرتجعات بالمحافظة', desc: 'توزيع المبيعات على خريطة المحافظات المصرية. معدلات الإرجاع بالمحافظة مع فلتر يستبعد المحافظات التي لديها أقل من ٥ طلبات — تجنباً لأرقام مضللة. اكتشف أين عملاؤك وأين مشكلاتك.', color: '' },
      { icon: Target, title: 'COD Aging — خريطة مخاطر التحصيل', desc: 'لقطة فورية لكل الطلبات المشحونة مصنَّفة بأيامٍ منذ الشحن. اكتشف الشحنات "العالقة" قبل أن تتحول لمرتجعات. نموذج Risk Management حقيقي لأصحاب المتاجر.', color: '' },
      { icon: Users, title: 'VIP الـ١٠ وتوزيع القيمة للعملاء', desc: 'قائمة أعلى ١٠ عملاء بإجمالي إنفاقهم. مخطط Customer Value Distribution: كم عميلاً ينفق ٠-٥٠٠ جنيه؟ كم ينفق ٥٠٠-١٠٠٠؟ وهكذا — افهم قاعدة عملائك واستهدف الشريحة الأكثر ربحاً.', color: '' },
      { icon: Megaphone, title: 'ROAS وCPO لكل حملة إعلانية', desc: 'Campaign Performance يعرض لكل حملة: الإنفاق الإعلاني، الإيراد، ROAS (= revenue ÷ spend)، وCPO (تكلفة الطلب الواحد). اعرف أي الحملات تُربحك وأيها يُشعل أموالك.', color: '' },
      { icon: Truck, title: 'أداء شركات الشحن مقارنةً', desc: 'CourierPerformance مبني من نفس استعلام المخططات بدون استعلام إضافي — صفر تكلفة إضافية. تسليم ومرتجع لكل شركة. متوسط أيام الإيصال بالمحطة. قرار التعاقد مبني على بيانات حقيقية.', color: '' },
      { icon: Star, title: 'أعلى المنتجات مبيعاً والأكثر إرجاعاً', desc: 'Top Products: الـ٥ الأكثر مبيعاً بالكمية. Top Returned Products: المنتجات الأكثر إرجاعاً بالكمية — راقب جودتك وقرر التوقف أو التحسين قبل أن تتراكم الخسائر.', color: '' },
    ],
  },
  walkthrough: {
    sectionLabel: 'كيف يعمل؟',
    title: 'من أول رقم إلى قرار مدروس',
    subtitle: '',
    tabs: [
      {
        id: 'kpis',
        label: 'مؤشرات الأداء',
        icon: Activity,
        imgSrc: './assets/dsh-2-list.png',
        imgAlt: 'مؤشرات الأداء الرئيسية والـ Sidebar الحي',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: '٦ KPIs فوق الصفحة — كلها مكاشة ذكياً', desc: 'كل أرقامك المهمة — زي إجمالي المبيعات، عدد الأوردرات اللي اتسلمت، اللي لسه بيتجهز، اللي في الشحن، المرتجعات، وحتى عدد عملائك اللي شغالين معاك — السيستم بيجمعها لحظة بلحظة من كل الطلبات الحالية والقديمة. والأرقام دي بتتحمل بسرعة صاروخ وبتتحدث تلقائياً، عشان تتابع حركة شغلك بالمليم ومن غير أي تأخير.' },
          { title: 'إيراد المُسلَّم محسوب بدقة لاين آيتم', desc: 'مكسبك اللي اتحقق بيتحسب بالقطعة مش بجمال الشيلة؛ يعني لو أوردر فيه 3 حتت والعميل استلم حتتين بس، السيستم بيحسبلك فلوس الحتتين اللي اتباعوا فعلاً. بكده أرقام مبيعاتك هتكون دقيقة جداً ومطابقة للي خرج من مخزنك ودخل جيبك بالظبط.' },
          { title: 'Quick Stats الصف السريع', desc: 'متوسط وقت الشحن بيتحسب بدقة من يوم ما الأوردر بيتعمل لحد ما بيطلع للشحن، ومعاه متوسط قيمة الأوردر، ونسبة العملاء اللي بيرجعوا يشتروا منك تاني، ومعدل نمو شغلك شهر بشهر.. كل دي مؤشرات بتظهرلك جاهزة ومباشرة من غير ما تضطر تعمل أي حسابات إضافية بنفسك.' },
          { title: 'Sidebar KPIs — النبض اللحظي', desc: 'القائمة الجانبية بتحدث نفسها كل ٣٠ ثانية عشان تنبهك بأي طلبات محتاجة تجهيز، شحنات متأخرة، بضاعة قربت تخلص، أو ديون لازم تتحصل، ده غير طلبات اليوم.. وحساب الخزنة بيظهرلك لحظة بلحظة مع كل حركة، عشان تبقى عارف وضعك المالي وتفاصيل شغلك طول الوقت ومن غير أي مجهود منك.' },
        ],
      },
      {
        id: 'charts',
        label: 'المخططات والتحليلات',
        icon: BarChart3,
        imgSrc: './assets/dsh-3-action.png',
        imgAlt: 'مخطط الاتجاهات مع الإيراد والربح وأداء شركات الشحن',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: 'Sales Trend: إيراد وربح في نفس المخطط', desc: 'المخطط يُبدِّل تلقائياً بين يومي (≤٣٠ يوم) وشهري (>٣٠ يوم). الإيراد = TotalAmount - ShippingFees + Deposit. الربح = الإيراد - CostAtSale × كمية الطلبات المُسلَّمة. الفجوة بينهما هي هامشك الحقيقي.' },
          { title: 'Status Comparison Donut — Delivered vs Returned', desc: 'Donut chart يُقارن Delivered+PartiallyDelivered ضد Returned+ShippedOnSender بعداد مباشر. نسبة الإيصال الحقيقية أمامك دائماً — ليس مجرد "كم طلب" بل "كم وصل للعميل".' },
          { title: 'Shipping Performance — أداء كل شركة شحن', desc: 'CourierPerformance مبني من نفس OrderChartRow query (لا استعلام إضافي). تسليم ومرتجع لكل شركة. COD Aging: لقطة آنية لكل الشحنات المعلَّقة مصنَّفة بالأيام منذ الشحن — رادار مخاطر التحصيل.' },
          { title: 'Order Types بالشهر — Exchange & Missing', desc: 'OrderTypesByMonth: عدد طلبات Exchange وMissing مجمَّعة شهرياً. راقب الاتجاه: هل مشاكل "البضاعة الناقصة" تزيد؟ هل العملاء يستبدلون أكثر؟ — مؤشر جودة التشغيل.' },
        ],
      },
      {
        id: 'geo',
        label: 'الجغرافيا والعملاء',
        icon: Map,
        imgSrc: './assets/dsh-4-details.png',
        imgAlt: 'تحليل جغرافي بالمحافظات وVIP Customers وتوزيع قيمة العملاء',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: 'توزيع المبيعات بالمحافظة', desc: 'SalesByGovernorate: أعلى ٥ محافظات بعدد الطلبات — اعرف كثافة عملائك جغرافياً. GovReturnRates: معدل الإرجاع بالمحافظة، لكن مع شرط: ≥٥ طلبات للمحافظة لإظهارها (تجنب أرقام مضللة من عينات صغيرة).' },
          { title: 'VIP Customers — أعلى ١٠ عملاء بالإنفاق', desc: 'قائمة مرتبة تنازلياً بإجمالي إنفاق كل عميل (هاتفه كـ identifier). بلِّط برنامج ولاء لأعلى ١٠ — أو على الأقل تعرَّف على من يستحق مزيداً من الاهتمام.' },
          { title: 'Customer Value Distribution — شرائح اللتفيل', desc: 'Histogram بشرائح الإنفاق (٠-٥٠٠ / ٥٠٠-١٠٠٠ / ...). كم عميلاً في كل شريحة؟ هل قاعدتك من الشرائح الدنيا أم العليا؟ فهم هذه الصورة يُغير استراتيجية التسعير.' },
          { title: 'New vs Returning Customers', desc: 'ReturningCustomersStats مبني بـ phone deduplication: مقارنة الهواتف عبر الفترة الحالية والتاريخية لتحديد من أول مشترٍ ومن عميل عائد. نسبة الولاء — أهم مقياس لصحة نشاطك.' },
        ],
      },
      {
        id: 'campaigns',
        label: 'الحملات والتوقيت',
        icon: Megaphone,
        imgSrc: './assets/dsh-5-extras.png',
        imgAlt: 'Campaign Performance مع ROAS وCPO وBest Days وTop Months',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: 'Campaign Performance: ROAS و CPO', desc: 'لكل حملة إعلانية: الإنفاق، الإيراد، ROAS = Revenue ÷ Spend، CPO = Spend ÷ Orders. ربط الإيراد بالحملة عبر CampaignId أو UTM — قرِّب إعلانك وحدِّد ما الذي يُدر أعلى عائد.' },
          { title: 'Best Days of Week — متى يشتري عملاؤك؟', desc: 'BestDays: توزيع الطلبات على أيام الأسبوع (الأحد - السبت). اعرف أي الأيام بها أعلى نشاط — جدوِّل حملاتك ومتابعتك لتوافق ذروة شرائهم.' },
          { title: 'Top Months — أفضل أشهرك تاريخياً', desc: 'TopMonthsSales: أعلى ٥ أشهر بإيراد التسليم الفعلي — مع عدد الطلبات. افهم موسميتك، خطِّط مخزونك للذروة، وتجنب الفشل في موسم الطلب العالي.' },
          { title: 'Moderator Performance — أداء الفريق', desc: 'SalesTeamPerformance: عدد الطلبات لكل Moderator في الفترة المختارة. مشرف يتعامل مع ١٠٠ طلب ضمن الفريق يستحق مكافأة — أو تدريباً إن كانت المرتجعات مرتفعة معه.' },
        ],
      },
    ],
  },
  faq: {
    title: <>لا تقمار — <span style={{ color: '#f43f5e' }}>كل رقم له مصدر.</span></>,
    subtitle: '',
    items: [
      { q: 'كيف يُحسَب الربح في مخطط Sales Trend؟', a: 'الربح = الإيراد − تكلفة البضاعة المباعة (COGS). COGS = SUM(CostAtSale × Quantity) للبنود (OrderItems) الموجودة في الطلبات المُسلَّمة فقط (Delivered + PartiallyDelivered). CostAtSale هو سعر التكلفة المسجَّل وقت البيع — يعكس التكلفة الفعلية لا التكلفة الحالية للمخزون.' },
      { q: 'ما الفرق بين نسبة النمو (MoM) والمقارنة المعتادة؟', a: 'المقارنة ليست مقيَّدة بشهر إلى شهر فقط — هي Period over Period. مثال: اخترت الفترة ١٥ مارس - ٢٨ مارس (١٤ يوم) → المقارنة تكون مع ١ مارس - ١٤ مارس (١٤ يوم). الفترة السابقة دائماً مطابقة في العدد. إذا كانت الفترة السابقة صفراً والحالية موجبة: النمو = +١٠٠٪.' },
      { q: 'كيف يعمل الكاش ومتى يتحدَّث؟', a: 'KPIs و Charts: تُكاش ١٠ دقائق بـ IMemoryCache مع CancellationChangeToken مرتبط بـ companyId. Sidebar: يُكاش ٣٠ ثانية للبيانات الهيكلية، رصيد الخزينة يُجلَب حياً. الإبطال الفوري: عند أي تغيير في بيانات الشركة (طلب جديد، شحن، إلخ) يُستدعى InvalidateDashboardCache(companyId) الذي يُلغي جميع إدخالات الكاش المرتبطة بها فوراً.' },
      { q: 'لماذا تُحسَب خسائر المرتجعات بهذه الطريقة؟', a: 'ReturnLossesAmount = جزءان: (١) SUM ExtraCost للطلبات ذات حالة "Shipped on Sender" — تكلفة الشحن العائد. (٢) SUM(RefurbCost × Quantity) من StockMovements من نوع "Quarantine_Valid" — تكلفة تجديد المنتج بعد ترميمه من الحجر الصحي. الجزء الثاني لا يُحسَب في أنظمة أخرى اعتيادياً — هذا يُعطيك الخسارة الحقيقية الكاملة.' },
      { q: 'كيف يُحدَّد العميل "العائد" في إحصاءات New vs Returning؟', a: 'Identifier الأساسي هو رقم الهاتف (CustomerPhone). النظام يجمع الهواتف من Orders + ArchivedOrders في الفترة الحالية، ثم يُقارنها بكل الفترات السابقة. إذا ظهر الهاتف في فترة سابقة → عميل عائد. إذا لم يظهر → عميل جديد. Deduplication بـ HashSet للدقة.' },
      { q: 'هل تظهر بيانات الطلبات المؤرشفة في اللوحة؟', a: 'نعم — كل استعلام يجمع LiveOrders(Orders) + ArchOrders(ArchivedOrders) في نفس المدى الزمني. مثال: CountNonCancelledOrders = CountLive + CountArch. هذا يمنع "فجوة" تاريخية في الإحصاءات عند أرشفة الطلبات القديمة.' },
      { q: 'ما هو COD Aging ولماذا هو مهم؟', a: 'COD Aging هو لقطة فورية (Point-in-Time) لكل الطلبات الحالية في حالة "Shipped" مصنَّفة بالأيام منذ تاريخ الشحن. مثال: ١٢ طلباً أُشحِنت منذ أكثر من ٢١ يوماً → خطر إرجاع مرتفع. يساعدك على المتابعة الاستباقية قبل أن تصبح مرتجعات رسمية وتُكبِّدك تكلفة الشحن العائد.' },
      { q: 'ما الفرق بين GovReturnRates و SalesByGovernorate؟', a: 'SalesByGovernorate: أعلى ٥ محافظات بعدد الطلبات الكلي. GovReturnRates: معدل الإرجاع = Returned / Total لكل محافظة — لكن مع شرط إظهار: ≥٥ طلبات للمحافظة. هذا الشرط يمنع أن تظهر محافظة بمعدل ١٠٠٪ بسبب طلب واحد مرتجع فقط.' },
      { q: 'كيف يرتبط Campaign Performance بالطلبات؟', a: 'كل طلب يحمل CampaignId أو UtmCampaign. النظام يُفسِّر الـ UTM ويُحوِّله لـ CampaignId ثم يُجمِّع الإيراد والطلبات لكل حملة. الإنفاق يأتي من جدول الحملات الإعلانية. ROAS = Revenue ÷ Spend، CPO = Spend ÷ Orders — هذان الرقمان يُحدِّدان ما إذا كان الإعلان مربحاً أم ضاراً.' },
    ],
  },
  related: {
    layout: 'modern',
    title: <>اللوحة تُلخِّص <span style={{ color: '#f43f5e' }}>كل وحداتك في مكان واحد</span></>,
    items: [
      { to: '/features/reports', icon: BarChart2, title: 'التقارير', body: 'بيانات اللوحة تُغذِّي تقارير مفصَّلة قابلة للتصدير — تعمُّق في أي رقم تراه على اللوحة.' },
      { to: '/features/expenses', icon: Wallet, title: 'المصروفات والخزينة', body: 'رصيد الخزينة في Sidebar يُجلَب مباشرةً من وحدة المصروفات — النبض المالي اللحظي.' },
      { to: '/features/inventory', icon: Boxes, title: 'إدارة المخزون', body: 'تنبيهات نفاد المخزون تظهر في Sidebar. CostAtSale في مخطط الربح يأتي من سجل تكاليف البضاعة.' },
      { to: '/features/shipping', icon: Truck, title: 'الشحن والتوصيل', body: 'Courier Performance وCOD Aging مشتقَّان من بيانات الشحن — رادار مخاطر التحصيل.' },
      { to: '/features/debts', icon: Landmark, title: 'المديونيات', body: 'الديون المتأخرة تظهر مباشرةً في Sidebar KPIs — وصول سريع لأداة التسوية.' },
      { to: '/features/preparation', icon: Package, title: 'التحضير', body: 'KPI card "To Prepare" يربطك مباشرةً بوحدة التحضير بنقرة — من الرقم للتنفيذ فوراً.' },
    ],
  },
  cta: {
    layout: 'modern',
    icon: LayoutDashboard,
    eyebrow: 'ابدأ الآن',
    title: <>هل تعرف ربحيتك <span style={{ color: '#f43f5e' }}>هذا الشهر بدقة؟</span></>,
    description: 'لا تكتفِ بمعرفة الإيراد — اعرف الربح الفعلي، معدل النمو، أفضل عملائك، وأفضل حملاتك. كل ذلك في لوحة واحدة، محدَّثة تلقائياً، على أي جهاز.',
    primaryLabel: 'ابدأ الآن مجاناً',
    secondaryLabel: 'استعرض الوحدات',
    secondaryToFeatures: true,
    trustBadges: [
      { icon: CheckCircle2, text: 'بدون بطاقة ائتمانية' },
      { icon: CheckCircle2, text: 'إعداد في أقل من ٥ دقائق' },
      { icon: CheckCircle2, text: 'دعم فني كامل بالعربية' },
    ],
  },
}
