import type { ModulePageConfig } from '../../types/module'
import {
  AlertTriangle,
  Ban,
  BarChart3,
  Boxes,
  Calculator,
  CheckCircle2,
  ClipboardList,
  FileSpreadsheet,
  History,
  Layers,
  Lock,
  Megaphone,
  PackagePlus,
  Phone,
  RefreshCcw,
  Shield,
  ShieldCheck,
  Truck,
  UserPlus,
  Users,
  Zap,
} from 'lucide-react'

export const orderEntryModuleConfig: ModulePageConfig = {
  layout: 'modern',
  theme: {
    rgba: 'rgba(132,204,22,',
    hex: '#84cc16',
    dim: 'rgba(132,204,22,0.12)',
    dark: '#65a30d',
    glow: '0 0 28px rgba(132,204,22,0.42)',
    linkHoverClass: 'hover:text-lime-400',
    relatedHoverBorderClass: 'hover:border-lime-500/40',
    relatedHoverTextClass: 'group-hover:text-lime-400',
  },
  back: {
    label: 'العودة إلى جميع الوحدات',
    linkToFeatures: true,
  },
  hero: {
    badgeIcon: Zap,
    badgeLabel: 'إدخال الطلبات',
    title: <>خلّص الأوردر <span style={{ color: '#84cc16' }}>وانت لسه على الشات.</span><br />أسرع إدخال. <span className="text-ocean-400">أقل أخطاء. تسليم أدق.</span></>,
    description: 'من رقم العميل إلى حفظ الأوردر في شاشة واحدة: اقتراح تلقائي لبيانات العميل من الهاتف، كشف تكرار خلال 24 ساعة، تحذير بلاك ليست، اختيار منتجات بالمتغيرات، وحساب إجمالي فوري (سعر الطلب + الشحن - العربون). نظام معمول للسرعة تحت ضغط الواتساب.',
    microStatsPills: [
      { icon: ClipboardList, label: '3 كروت إدخال مركزة' },
      { icon: Phone, label: 'تحذير رقم مكرر 24 ساعة' },
      { icon: ShieldCheck, label: 'حالة مبدئية ذكية من المخزون' },
    ],
    primaryCtaLabel: 'ابدأ الآن مجاناً',
    secondaryCtaLabel: 'اكتشف كل الوحدات',
    secondaryCtaToFeatures: true,
    image: {
    src: './assets/ord-1-hero.png',
    alt: 'شاشة إدخال الطلبات السريعة',
    width: 780,
    height: 480,
    loading: 'eager',
  },
    imageAnimation: 'modern',
  },
  pain: {
    stats: [
      { icon: Zap, value: 'الدقيقة = بيع', label: 'العميل على واتساب لا ينتظر واجهة بطيئة. كل تأخير يعني احتمال فقد أوردر. هنا الإدخال مصمم لتقليل عدد النقرات لأقصى حد مع اقتراحات تلقائية من بيانات سابقة.' },
      { icon: AlertTriangle, value: 'غلطة رقم = شحنة غلط', label: 'رقم هاتف خطأ أو رقم متكرر في نفس اليوم ممكن يعمل شحنة مكررة أو متابعة غلط. النظام ينبهك عند تكرار الرقم خلال آخر 24 ساعة ويعرض OrderCode المرتبط فوراً.' },
      { icon: Layers, value: 'تعقيد = أخطاء', label: 'الموديريتور يحتاج تدفق واضح: عميل، تفاصيل، فلوس. أي تشتيت يزود أخطاء. لذلك الصفحة مقسمة 3 كروت منطقية مع تحقق فوري على الحقول المهمة قبل الحفظ.' },
    ],
  },
  value: {
    sectionLabel: 'قيمة الوحدة',
    title: 'سرعة فريق المبيعات + دقة عمليات الشحن',
    subtitle: 'Order Entry هنا ليس فورم تقليدي. هو تدفق تشغيلي كامل: إدخال سريع، تحقق ذكي، حماية من التكرار، وربط مباشر بالمخزون والحملات والسجل التدقيقي.',
    cards: [
      { icon: RefreshCcw, title: 'Order ID تلقائي سريع وذكي', desc: 'GetNextOrderId لا يعمل loop على كل الأوردرات. الخدمة تحسب أكبر رقم مباشرة في SQL من orders + archived_orders مع REGEXP_REPLACE، ثم +1. أسرع مع أحجام بيانات كبيرة.', color: '' },
      { icon: UserPlus, title: 'إنشاء/تحديث عميل تلقائي من الهاتف', desc: 'أول ما تدخل Phone1، النظام يبحث في العملاء ويملأ الاسم والمحافظة والعنوان عند وجود تطابق. عند الحفظ، EnsureCustomerExists يعمل upsert آمن ويحدث بيانات العميل تلقائياً.', color: '' },
      { icon: Phone, title: 'تنبيه رقم مكرر خلال آخر 24 ساعة', desc: 'Endpoint مخصص check-recent-phone يفحص CreatedAtUtc خلال آخر 24 ساعة ويعرض OrderCode الحديث. النتيجة: تقليل أخطاء التكرار أثناء زحمة الشات.', color: '' },
      { icon: Ban, title: 'تحذير عميل بلاك ليست واضح', desc: 'بحث العميل يرجّع IsBlacklisted وBlacklistReason. الواجهة تعرض تحذيراً أحمر قوي مع السبب والتنبيه التشغيلي، حتى لا يتم تمرير أوردر عالي المخاطرة بدون وعي.', color: '' },
      { icon: PackagePlus, title: 'اختيار منتجات بالمتغيرات + تسعير مرن', desc: 'كل سطر منتج يختار Variant، ويجلب سعره الافتراضي من الكتالوج، مع إمكانية تعديل Unit Price يدوياً لكل سطر. إضافة/حذف سطور فوري بدون إعادة تحميل.', color: '' },
      { icon: Calculator, title: 'حساب مالي مباشر مع زر مزامنة', desc: 'إجمالي الطلب = OrderPrice + Shipping - Deposit. يوجد زر يحول OrderPrice تلقائياً إلى مجموع السطور (lines subtotal) مع خيار Manual Override عند الحاجة.', color: '' },
      { icon: Users, title: 'تعيين موديريتور تلقائي ذكي', desc: 'النظام يجلب الموديريتورز من Staff أولاً، ولو فاضي يرجع لـ Users. يختار اسم المستخدم الحالي تلقائياً لو مطابق، أو يختار الوحيد المتاح. يقلل خطوات ما قبل الحفظ.', color: '' },
      { icon: Megaphone, title: 'ربط اختياري بالحملات الإعلانية', desc: 'يمكن إسناد CampaignId أثناء الإدخال من الحملات النشطة فقط. هذا يربط المبيعات مباشرة بمصدر الإعلان، ويخدم ROAS/CPA/Delivery analytics لاحقاً بدون عمل إضافي.', color: '' },
      { icon: Shield, title: 'حالة مبدئية من المخزون الحقيقي', desc: 'قبل الحفظ، CreateOrder يقفل صفوف variants المطلوبة بـ FOR UPDATE ثم يفحص CurrentStock. لو في نقص: status = Shortage. لو كافي: To prepare. هذا يمنع race condition في الطلبات المتزامنة.', color: '' },
      { icon: Lock, title: 'تقييد تعديل الموديريتور حسب الحالة', desc: 'الموديريتور يقدر يعدل فقط حالات New / To prepare / Shortage / Deferred. أي حالة شحن/نهائية تظهر كنموذج read-only مع banner واضح، وتُرفض backend كذلك إذا كانت Locked.', color: '' },
      { icon: History, title: 'Audit كامل لكل تعديل', desc: 'كل عمليات bulk والتحديثات تضيف AuditLog بتفاصيل من/إلى. يوجد modal لعرض Order Audit (Admin only) + mini audit في الفورم (created/last modified by). تدقيق جاهز وقت النزاع.', color: '' },
      { icon: FileSpreadsheet, title: 'استيراد إكسيل احترافي على 3 مراحل', desc: 'Preview validation بدون حفظ، Confirm للحفظ، وImport-bulk chunked للأحجام الكبيرة. يدعم 18 عموداً، قوالب جاهزة، تحويل محافظ عربي/إنجليزي، وحماية updateExisting على حالات محظورة للشحن/النهائي.', color: '' },
    ],
  },
  walkthrough: {
    sectionLabel: 'خط سير العمل',
    title: 'من محادثة العميل إلى أوردر نظيف وجاهز للتنفيذ',
    subtitle: '',
    tabs: [
      {
        id: 'create',
        label: 'إنشاء الأوردر السريع',
        icon: Zap,
        imgSrc: './assets/ord-2-list.png',
        imgAlt: 'فورم إدخال الطلبات السريع',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: 'ابدأ من Phone1 — النظام يكمل الباقي', desc: 'اكتب رقم العميل، والواجهة تبحث تلقائياً في العملاء. لو العميل موجود: يملأ الاسم/المحافظة/العنوان. لو صيغة الرقم مش مصرية صحيحة يظهر warning. لو رقم مكرر خلال 24 ساعة يظهر تنبيه مع OrderCode.' },
          { title: 'اختار الموديريتور تلقائياً', desc: 'اللستة تُجلب من Staff (Moderator active) ولو غير متاحة تستخدم Users. إذا اسمك موجود يختارك تلقائياً. هذا يخلي الفورم جاهز أسرع للفريق.' },
          { title: 'أضف المنتجات كسطور Variant', desc: 'كل سطر = Variant + Qty + UnitPrice. السعر الافتراضي يأتي من الكتالوج مع إمكانية تعديل يدوي. يوجد add/remove rows بدون أي lag.' },
          { title: 'احسب الإجمالي واحفظ', desc: 'OrderPrice + Shipping - Deposit = Total. زر الحاسبة يرجع OrderPrice لمجموع السطور. عند الحفظ: النظام ينشئ/يحدث العميل تلقائياً ويربط الأوردر بالحملة لو اخترتها.' },
        ],
      },
      {
        id: 'safety',
        label: 'الدقة ومنع الأخطاء',
        icon: Shield,
        imgSrc: './assets/ord-3-action.png',
        imgAlt: 'التحقق الذكي ومنع الأخطاء',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: 'Validation قبل أي Save', desc: 'الحقول الأساسية إلزامية: Phone1, CustomerName, Governorate, Address, OrderId, OrderDate, Moderator. لازم سطر منتج واحد على الأقل مع qty > 0 وسعر صحيح.' },
          { title: 'Stock-aware initial status', desc: 'الخدمة تقفل صفوف variants المطلوبة بـ FOR UPDATE ثم تقارن الكميات بالمخزون. لو في shortage في أي سطر: الأوردر يبدأ Shortage، غير ذلك يبدأ To prepare.' },
          { title: 'تحديث آمن للحالات المقفولة', desc: 'الأوردرات التي شُحنت أو أُغلقت (Shipped/Delivered/Returned/Cancelled...) تعتبر locked للتعديل من order entry. هذا يوقف أي تعديل متأخر يسبب تضارب مع الشحن أو الحسابات.' },
          { title: 'Duplicate-safe customer upsert', desc: 'لو طلبان متزامنان حاولوا إنشاء نفس الهاتف، unique key يلتقط السباق والخدمة تعيد جلب العميل الفائز بدلاً من الفشل. النتيجة: بدون duplication في customer master.' },
        ],
      },
      {
        id: 'ops',
        label: 'إدارة القائمة والعمليات',
        icon: ClipboardList,
        imgSrc: './assets/ord-4-details.png',
        imgAlt: 'قائمة الطلبات والعمليات المجمعة',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: 'بحث قوي + فلترة + ترتيب Server-side', desc: 'بحث بالـ order code/العميل/الهاتف مع فلتر status/date range/page/sort. backend يطبق whitelist للترتيب ويعمل pagination. الأداء ثابت حتى مع حجم بيانات كبير.' },
          { title: 'عمليات bulk بتقرير نجاح/فشل واضح', desc: 'تغيير حالة، إسناد شركة شحن، حذف، إلغاء، إسناد حملة على دفعة أوامر. كل عملية ترجع successCount/failedCount/errors وتظهر للمستخدم ملخصاً فورياً.' },
          { title: 'نسخ رسالة واتساب بنقرة', desc: 'copyOrderToClipboard يبني رسالة موحدة من بيانات الأوردر (العميل، الهاتف، العنوان، الإجمالي). مفيد للموديريتور في التأكيد مع العميل بسرعة وبنفس الصيغة كل مرة.' },
          { title: 'تصدير Excel جاهز للمراجعة', desc: 'Orders/export ينزل ملف XLSX بالأعمدة التشغيلية الأساسية (الأوردر، العميل، المنتجات، المحافظة، الحالة، الشحن، الاستحقاق). مناسب للتسليم اليومي والمتابعة الخارجية.' },
        ],
      },
      {
        id: 'import',
        label: 'الاستيراد والتدقيق',
        icon: FileSpreadsheet,
        imgSrc: './assets/ord-5-extras.png',
        imgAlt: 'الاستيراد والتحقق والتدقيق',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: 'Import Template رسمي 18 عمود', desc: 'قالب جاهز بترتيب ثابت: OrderCode, Type, Moderator, Date, CustomerName... Campaign. يقلل مشاكل mapping اليدوي ويجعل الاستيراد متوافق من أول مرة.' },
          { title: 'Preview قبل الحفظ', desc: 'import/preview يقرأ الإكسيل ويصنف valid/invalid rows مع أسباب دقيقة. لا شيء يُحفظ قبل المراجعة. هذا يمنع إدخال بيانات مكسورة لقاعدة الإنتاج.' },
          { title: 'Normalize ذكي للبيانات', desc: 'يدعم تحويل المحافظ عربي/إنجليزي لنفس canonical value، وتحويل OrderType عربي/إنجليزي. يمنع تحديث أوردرات في حالات نهائية أثناء updateExisting لحماية بيانات الشحن النهائية.' },
          { title: 'Bulk chunked import للأحجام الكبيرة', desc: 'import-bulk مصمم لدفعات frontend chunked (100 صف/دفعة) لسرعة أعلى وتقليل timeouts مقارنةً بإرسال ملف ضخم في طلب واحد.' },
        ],
      },
    ],
  },
  faq: {
    title: <>إدخال أسرع. <span style={{ color: '#84cc16' }}>تشغيل أأمن.</span></>,
    subtitle: '',
    items: [
      { q: 'كيف النظام يمنع تكرار نفس العميل أثناء زحمة الإدخال؟', a: 'في الواجهة يوجد فحص duplicate phone خلال 24 ساعة (check-recent-phone) مع عرض OrderCode، وفي backend EnsureCustomerExists يعتمد على unique (company,phone) ويتعامل مع race condition: لو حصل تضارب insert متزامن، يقرأ السجل الموجود بدلاً من تكراره.' },
      { q: 'هل يمكن تعديل أوردر بعد ما يتشحن؟', a: 'لا من order entry. هناك قائمة حالات locked تشمل shipped/finalized (Delivered, Returned, Damaged, Cancelled وغيرها). الموديريتور تحديداً مقيد بحالات New, To prepare, Shortage, Deferred فقط.' },
      { q: 'كيف يتم تحديد حالة الأوردر أول مرة؟', a: 'عند create، الخدمة تقفل صفوف variants المطلوبة FOR UPDATE ثم تقارن quantity المطلوبة بالمخزون الحالي. إذا أي سطر أعلى من stock -> Shortage، غير ذلك -> To prepare. هذا قرار تلقائي مبني على بيانات لحظية آمنة من التزامن.' },
      { q: 'هل أسعار السطور هي المعتمدة أم سعر الطلب اليدوي؟', a: 'الواجهة تدعم الاثنين: OrderPrice يمكن إدخاله يدوياً، أو مزامنته بزر الحاسبة مع line subtotal. الإجمالي النهائي دائماً = OrderPrice + ShippingPrice - Deposit، ويُرسل للـ API بهذه الصيغة.' },
      { q: 'هل الوحدة تدعم ربط الأوردر بحملة إعلانية؟', a: 'نعم. في الفورم حقل campaign اختياري من الحملات النشطة. يتم إرسال CampaignId مع الأوردر، ما يسمح بربط المبيعات بمصدر الإعلان تلقائياً في تحليلات Ads.' },
      { q: 'ما الفرق بين preview وconfirm في الاستيراد؟', a: 'preview يقرأ ويحلل الإكسيل فقط ويعيد valid/invalid rows دون حفظ. confirm يحفظ الصفوف المعتمدة. هذا يقلل المخاطر ويعطي فرصة مراجعة الأخطاء قبل لمس قاعدة البيانات.' },
      { q: 'هل يوجد تتبع لمن عدّل الأوردر؟', a: 'نعم. الطلب يحمل createdBy/lastModified وtimestamps، ويوجد endpoint audit خاص بالأوردر (Admin only) يعرض history للتغييرات. كما أن عمليات bulk تضيف AuditLog واضح لكل عملية.' },
      { q: 'كيف أحول بيانات الأوامر إلى تقارير خارجية؟', a: 'يمكنك تصدير أوامرك إلى Excel من endpoint export بنفس فلاتر البحث (status/date/q). الملف يتضمن بيانات العميل، المنتجات، الإجمالي، الحالة، الشحن، وتواريخ التنفيذ للمراجعة السريعة.' },
    ],
  },
  related: {
    layout: 'modern',
    title: <>إدخال الطلب هو <span style={{ color: '#84cc16' }}>بداية سلسلة التنفيذ بالكامل</span></>,
    items: [
      { to: '/features/preparation', icon: PackagePlus, title: 'التحضير', body: 'حالة To prepare/Shortage الخارجة من Order Entry هي نقطة البداية المباشرة لفريق التحضير. كلما كان الإدخال أنظف، كان التنفيذ أسرع وأقل ارتجاع.' },
      { to: '/features/shipping', icon: Truck, title: 'الشحن', body: 'Bulk assign courier + بيانات عنوان/محافظة دقيقة من البداية تقلل أخطاء التسليم. أي خطأ في الإدخال ينعكس فوراً على تكلفة الشحن ونسبة التسليم.' },
      { to: '/features/inventory', icon: Boxes, title: 'المخزون', body: 'الربط المباشر مع variants والمخزون وقت الإنشاء يحدد shortage تلقائياً. هذا يمنع بيع وهمي ويعطي الفريق رؤية صحيحة قبل الالتزام مع العميل.' },
      { to: '/features/ads', icon: Megaphone, title: 'الحملات الإعلانية', body: 'اختيار Campaign أثناء الإدخال يجعل كل أوردر قابل للإسناد التسويقي لاحقاً. هذا هو الأساس الحقيقي لحساب ROAS وCPA من بيانات تشغيلية دقيقة.' },
      { to: '/features/staff', icon: Users, title: 'فريق العمل', body: 'اسم الموديريتور المرتبط بكل أوردر يدخل في قياس الأداء والعمولات. كلما كان الإسناد أدق في Order Entry، كانت رواتب العمولة أعدل وأسهل في المراجعة.' },
      { to: '/features/reports', icon: BarChart3, title: 'التقارير', body: 'Excel export + البيانات المنظمة في order list تغذي تقارير الأداء اليومية بسرعة. من دون جهد إضافي تحصل على رؤية واضحة لحجم المبيعات وحالات التشغيل.' },
    ],
  },
  cta: {
    layout: 'modern',
    icon: Zap,
    eyebrow: 'ابدأ الآن',
    title: <>جاهز تحول إدخال الأوردر من <span style={{ color: '#84cc16' }}>عنق زجاجة</span> إلى محرك مبيعات؟</>,
    description: 'خلّي فريقك ينجز أسرع وهو أهدى: تدفق واضح، تحقق ذكي، حماية من التكرار، وربط مباشر بالشحن والمخزون والحملات. كل هذا في شاشة واحدة مصممة لواقع الشغل اليومي.',
    primaryLabel: 'ابدأ الآن مجاناً',
    secondaryLabel: 'استعرض الوحدات',
    secondaryToFeatures: true,
    trustBadges: [
      { icon: CheckCircle2, text: 'إدخال أسرع تحت الضغط' },
      { icon: CheckCircle2, text: 'أخطاء أقل قبل الشحن' },
      { icon: CheckCircle2, text: 'رؤية أوضح لأداء الفريق' },
    ],
  },
}
