import type { ModulePageConfig } from '../../types/module'
import {
  Activity,
  AlertTriangle,
  BarChart3,
  Boxes,
  BrainCircuit,
  Calculator,
  CheckCircle2,
  Clock,
  Download,
  FileSpreadsheet,
  FileText,
  Landmark,
  LayoutDashboard,
  RefreshCw,
  Scale,
  Settings,
  ShieldCheck,
  Sliders,
  Target,
  TrendingDown,
  Truck,
  Users,
  Wallet,
} from 'lucide-react'

export const reportsModuleConfig: ModulePageConfig = {
  layout: 'modern',
  theme: {
    rgba: 'rgba(139,92,246,',
    hex: '#8b5cf6',
    dim: 'rgba(139,92,246,0.12)',
    dark: '#7c3aed',
    glow: '0 0 28px rgba(139,92,246,0.40)',
    linkHoverClass: 'hover:text-violet-400',
    relatedHoverBorderClass: 'hover:border-violet-500/40',
    relatedHoverTextClass: 'group-hover:text-violet-400',
  },
  back: {
    label: 'العودة إلى جميع الوحدات',
    linkToFeatures: true,
  },
  hero: {
    badgeIcon: FileText,
    badgeLabel: 'التقارير المالية والذكاء التجاري',
    title: <>ميزانيتك الحقيقية — <span style={{ color: '#8b5cf6' }}>في ثوانٍ، لا ساعات.</span><br />ROI. هامش الربح. <span className="text-ocean-400">تحليل CFO.</span></>,
    description: 'الخلاصة المالية لشغلك في مكان واحد؛ 9 مؤشرات أساسية و10 نسب مالية دقيقة بتديك تقييم محترف لبيزنسك، السيستم بيجمعها من كل حتة في ثواني. تقدر كمان تجرب سيناريوهات مختلفة لمستقبل شغلك، تطلع تقارير Excel وPDF، وتدير حسابات شركائك وتوزع الأرباح بينهم بالمليم ومن غير غلطة.',
    microStatsPills: [
      { icon: Calculator, label: '٩ KPIs + ١٠ نسب CFO' },
      { icon: Sliders, label: 'محاكاة سيناريوهات لحظية' },
      { icon: Download, label: '٦ تصديرات Excel + PDF' },
    ],
    primaryCtaLabel: 'ابدأ الآن مجاناً',
    secondaryCtaLabel: 'اكتشف كل الوحدات',
    secondaryCtaToFeatures: true,
    image: {
    src: './assets/rpt-1-hero.png',
    alt: 'لوحة التقارير المالية',
    width: 780,
    height: 480,
    loading: 'eager',
  },
    imageAnimation: 'modern',
  },
  pain: {
    stats: [
      { icon: Clock, value: 'ساعات', label: 'يقضيها المدير المالي يدوياً في جمع الأرقام من إكسيل ومنصات الشحن والمصروفات — وقت يُنجزه النظام في أقل من ثانية واحدة بـ Task.WhenAll.' },
      { icon: AlertTriangle, value: '٦٧٪', label: 'من قرارات التسعير في المتاجر الصغيرة تُبنى على الإيراد لا الربح الحقيقي — لأن حساب COGS يدوياً معقول جداً. هنا يحسبه النظام تلقائياً من OrderItems.' },
      { icon: TrendingDown, value: '٤٢٪', label: 'من الشركاء يكتشفون أخطاء في توزيع الأرباح بعد سنة — لأن حساب "Effective Capital = رأس المال + الإيداعات - السحوبات" لم يُطبَّق بدقة. هنا مُؤتمَت بالكامل.' },
    ],
  },
  value: {
    sectionLabel: 'لماذا التقارير المالية؟',
    title: 'ليست مجرد أرقام — هي قرارات مبنية على بيانات.',
    subtitle: 'من صحة السيولة الشهرية إلى ROAS الحملات وأيام بيع المخزون — وحدة التقارير تُغطي كل ما يحتاجه صاحب المتجر ورئيس المالية في آنٍ واحد.',
    cards: [
      { icon: Calculator, title: '٩ KPIs بحوسبة متوازية — من ٥ قواعد بيانات', desc: 'كل أرقامك المالية المهمة — زي صافي الإيرادات والأرباح، قيمة أصولك، السيولة المتاحة، وهامش ربحك، وحتى معدل المصاريف والوقت اللي السيولة الحالية تقدر تغطيه — السيستم بيحسبها لك كلها في وقت واحد ومن كل الحسابات. مفيش ثانية انتظار، الخلاصة دايمًا جاهزة قدامك عشان تقرر صح.', color: '' },
      { icon: BrainCircuit, title: '١٠ نسب مالية لمستوى CFO', desc: 'كل النسب اللي بتعرفك صحة بيزنسك — من أول هامش الربح ومصاريف التشغيل، لحد سرعة دوران بضاعتك في المخزن ومواعيد تحصيل فلوسك من السوق — السيستم بيحسبها لك كلها مرة واحدة من بياناتك الحالية. كل النسب دي بتظهرلك فوراً ومن غير أي تحميل زيادة أو انتظار، عشان تديك صورة كاملة وحقيقية عن كفاءة شغلك.', color: '' },
      { icon: Scale, title: 'ميزانية مفصَّلة: ٨ أصول + ٥ خصوم', desc: 'الأصول: الخزينة، المخزون (CurrentStock × CostPrice)، قروض الموظفين، المستحقات اليدوية، قيمة الشحنات النشطة، رصيد Shipping Ledger، قيمة Pipeline، الأصول الثابتة. الخصوم: رواتب معلَّقة، مدفوعات مستحقة، تكلفة إعادة التخزين، ديون Ledger، غرامات الإرجاع.', color: '' },
      { icon: Sliders, title: 'محاكاة سيناريوهات "ماذا لو؟"', desc: 'درِّج معدل التسليم (٠-١٠٠٪)، معدل تسييل المخزون (٠-١٠٠٪)، وضع Pipeline (كل الطلبات / الجاهز فقط)، تكلفة الإرجاع/المشرف/التغليف لكل طلب — النظام يحسب Simulated Equity وSimulated Profit وROI فورياً.', color: '' },
      { icon: FileSpreadsheet, title: '٦ تصديرات Excel (ClosedXML)', desc: 'Full Orders (١٨٠ يوم كحد أقصى)، Products (تكلفة + سعر بيع)، Shipping Performance (٣٦٦ يوم)، Sales Team Performance، Financial Summary، Inventory Valuation — كلها XLSX جاهزة للفتح في Excel مباشرةً.', color: '' },
      { icon: FileText, title: 'تقرير PDF احترافي (QuestPDF)', desc: 'تقرير A4 بصورة العلامة التجارية: CFO KPIs، جدول KPIs الرئيسي، ميزانية الأصول/الخصوم، شرح صيغ المؤشرات (Explainable BI)، جدول الشركاء — بالعربي (RTL) أو الإنجليزي كامل الخيار.', color: '' },
      { icon: Activity, title: 'تسوية مالية بالفترة (Financial Settlement)', desc: 'حدد أي فترة زمنية تختارها، والسيستم هيحسبلك فوراً: مبيعاتك، تكلفة البضاعة اللي اتباعت، مصاريف الشحن، وكمان مرتبات الموظفين اللي اندفعت، ومصاريف إعلاناتك وأي مصاريف تانية.. وفي الآخر يطلعلك مكسبك الصافي، ومعدل العائد من إعلاناتك، ونسبة استثمارك في الفترة دي بالظبط، عشان تعرف كل قرش صرفته رجعلك قد إيه.', color: '' },
      { icon: BarChart3, title: 'Sales Summary بلوحة يومية وشهرية', desc: 'تقدر تعرض مبيعاتك، وتكلفة البضاعة، وصافي ربحك بالتاريخ اللي تحبه، سواء يوم بيوم أو شهر بشهر. السيستم بيحسب التكلفة بدقة من واقع كل صنف اتبع في لحظتها، وبيجمع بياناتك الحالية والقديمة المتأرشفة مع بعض أوتوماتيك، عشان يديك تقرير مالي كامل ومظبوط عن أي فترة تختارها.', color: '' },
      { icon: Users, title: 'إدارة الشركاء وتوزيع الأرباح', desc: 'أضف شركاء بحصص % ورأس مال. إيداعات وسحوبات ورفع رأس المال — كلها في سجل شفاف. Distribution Base = Adjusted Equity - Effective Capital. شرط ١٠٠٪ على الحصص قبل إغلاق الفترة أو خروج الشريك.', color: '' },
      { icon: RefreshCw, title: 'إغلاق الفترة المالية', desc: 'أغلق الفترة: يُؤرشَف صافي حقوق الملكية كـ Opening Capital للفترة التالية، تُحوَّل مستحقات الشركاء لـ Debts. شرط: مجموع الحصص = ١٠٠٪ بالضبط — وإلا يُرفَض الإغلاق.', color: '' },
      { icon: Target, title: 'خروج الشريك بتسوية كاملة', desc: 'عند خروج شريك: تحكَّم في تقييم الأصول الثابتة ونسبة تسييل المخزون. النظام يحسب صافي المستحق (Net Payout) فورياً. ادفع من الخزينة أو أنشئ مديونية بتاريخ استحقاق. حصته تُعاد توزيعها على الشركاء المتبقين.', color: '' },
      { icon: ShieldCheck, title: 'Explainable BI — كل رقم بصيغته', desc: 'كل من ٩ KPIs يحمل kpiBreakdowns: صيغة JSON تشرح مكوناته. مثال: Net Equity = {assets, liabilities, result}. اضغط على أي بطاقة مؤشر لترى المكونات الحقيقية — لا صناديق سوداء.', color: '' },
    ],
  },
  walkthrough: {
    sectionLabel: 'كيف يعمل؟',
    title: 'من بيانات خام إلى تقرير مالي محكم',
    subtitle: '',
    tabs: [
      {
        id: 'kpis',
        label: 'المؤشرات الجوهرية',
        icon: Calculator,
        imgSrc: './assets/rpt-2-list.png',
        imgAlt: 'لوحة KPIs — ٩ مؤشرات جوهرية + ١٠ نسب CFO',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: '٩ KPIs محسوبة bمتوازياً من ٥ مصادر', desc: 'Net Revenue يجمع Orders + ArchivedOrders. Net Profit = Revenue - Total Expenses. Net Equity = Assets - Liabilities. Burn Rate = متوسط OPEX الشهري (يُستبعد Ads وGoods Purchase وRestock وShipping من حساب الـ OPEX). كل مجموعة تعمل على DbContext مستقل.' },
          { title: 'ROI وRoyalty وProfit Margin بدقة أربعة أرقام', desc: 'ROI = Net Profit ÷ Opening Capital × ١٠٠. Opening Capital يُقرأ من آخر Financial Period المُغلقة، وإن لم توجد فمن مجموع InitialCapital للشركاء. Profit Margin محسوبة بنسبة ٤ خانات عشرية — لا تقريب مبكر.' },
          { title: 'Runway: كم شهراً يبقى السيولة؟', desc: 'Runway = Net Liquidity ÷ Burn Rate. Net Liquidity = (Cash + In-Shipping + Pipeline) - Total Liabilities. إذا كانت السيولة سالبة أو Burn Rate صفراً → Runway = 0 (لا قيم x سالبة أو ∞). مؤشر إنذار مبكر حقيقي.' },
          { title: 'CFO Mode — ١٠ نسب تحليلية متقدمة', desc: 'Gross Profit Margin (Revenue - COGS)، Inventory Turnover (COGS ÷ Inventory Value)، DSO = (AR ÷ Revenue × ٣٦٥) — أيام تحصيل المبيعات. AP Days = (AP ÷ COGS × ٣٦٥). Debt-to-Equity Ratio. كلها تُحسَب بدون استعلام إضافي فوق Core KPIs.' },
        ],
      },
      {
        id: 'simulation',
        label: 'محاكاة السيناريوهات',
        icon: Sliders,
        imgSrc: './assets/rpt-3-action.png',
        imgAlt: 'محرك السيناريوهات — درجة التسليم، تسييل المخزون، تكاليف الوحدة',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: 'محرك السيناريوهات — "ماذا لو سلَّمت ٨٠٪ فقط؟"', desc: 'Delivery Rate (٠-١٠٠٪): تطبيق على pipeline و in-shipping — يحسب الإيراد المتوقع. Pipeline Mode: "Ship All" يُضيف تكلفة تصفير المخزون كالتزام، "Ship Ready Only" يقصر التحليل على الطلبات الجاهزة. الفرق واضح في Simulated Equity مباشرةً.' },
          { title: 'معدل تسييل المخزون وتكاليف الوحدة', desc: 'Inventory Liquidation Rate (٠-١٠٠٪): ما قيمة مخزونك لو اضطررت لبيعه بعجلة؟ تكاليف الوحدة: تكلفة الإرجاع لكل طلب، مكافأة المشرف للطلب الناجح، تكلفة التغليف لكل طلب — كلها تُضرَب في عدد الطلبات المقابلة وتُطرَح من الربح المحاكَى.' },
          { title: 'النتيجة الكاملة للسيناريو: ٨ أرقام', desc: 'SimulatedEquity، SimulatedProfit، ROI المحاكَى، NetLiquidity، WorkingCapital، TotalAssets، TotalLiabilities — بالإضافة لـ AssetsBreakdown وLiabilitiesBreakdown مفصَّلَيْن (٨ بنود للأصول، ٥ للخصوم). كل شيء في استجابة API واحدة.' },
          { title: 'مُعدَّل التسليم الضمني (Implied Delivery Rate)', desc: 'قبل تشغيل المحاكاة، النظام يحسب معدل التسليم الفعلي من سجلاتك التاريخية ويملأ الـ Slider تلقائياً — انطلاقاً من واقعك لا من افتراضك. هذا يجعل المحاكاة نقطة بداية واقعية لا خيالية.' },
        ],
      },
      {
        id: 'settlement',
        label: 'التسويات والتصدير',
        icon: FileSpreadsheet,
        imgSrc: './assets/rpt-4-details.png',
        imgAlt: 'التسوية المالية والتصدير Excel وPDF',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: 'Financial Settlement — P&L حقيقي بالفترة', desc: 'حدِّد أي نطاق زمني: النظام يحسب الإيراد، COGS (JOIN مباشر على OrderItems — لا round-trips)، تكلفة الشحن، رواتب الموظفين المُدفوعة خلال الفترة، الإنفاق الإعلاني، المصاريف الأخرى. Net Profit = Revenue - Total Costs. ROAS = Revenue ÷ Ad Spend.' },
          { title: 'Sales Summary — يومي أو شهري مع Profit', desc: 'Revenue + COGS + Gross Profit لكل يوم أو شهر. COGS مجمَّع بـ JOIN مباشر على OrderItems في PostgreSQL — يعيد ≤٤ × ٣٦٦ صفاً مجمَّعاً للدمج في الذاكرة. بيانات الأرشيف مدمجة تلقائياً. يُمنع نطاق أكثر من ٣٦٦ يوماً لحماية الأداء.' },
          { title: '٦ تصديرات Excel بـ ClosedXML', desc: 'Full Orders: كل الطلبات بحقولها (١٨٠ يوم). Products: منتجات بتكلفة وسعر بيع ومخزون. Shipping Performance: أداء شركات الشحن بالتسليم والإرجاع وأيام التوصيل. Sales Team: مؤشرات المشرفين. Financial Summary: ملخص مالي شامل. Inventory Valuation: التكلفة + سعر البيع لكل variant.' },
          { title: 'PDF تقرير A4 بالعربي/الإنجليزي', desc: 'تقرير QuestPDF كامل: شعار الشركة، تاريخ التوليد، CFO KPIs، جدول المؤشرات الرئيسية، ميزانية الأصول والخصوم، قسم شرح الصيغ (Explainable BI)، جدول الشركاء — مع أرقام الصفحات. دعم RTL كامل للعربي.' },
        ],
      },
      {
        id: 'partners',
        label: 'الشركاء والأرباح',
        icon: Users,
        imgSrc: './assets/rpt-5-extras.png',
        imgAlt: 'إدارة الشركاء — توزيع الأرباح وخروج الشريك وإغلاق الفترة',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: 'ميزانية الشركاء: حصة، رأس مال، Effective Capital', desc: 'كل شريك له: حصة % من الأرباح، رأس مال مبدئي. Effective Capital = InitialCapital + Injections - Withdrawals (كل السجلات التاريخية). Distribution Base = Net Equity المُعدَّل - Effective Capital الكلي. هذا هو ما يُوزَّع فعلياً على الشركاء بنسبهم.' },
          { title: 'سجل المعاملات: سحب، إيداع، زيادة رأس المال', desc: 'لكل شريك: أضف سحباً (Withdrawal)، حقن نقدي (Cash Injection)، أو زيادة رأس مال (Capital Increase) — كلها مُسجَّلة بالتاريخ والملاحظة. عرض التاريخ الكامل بنقرة. التحقق من الخزينة قبل أي سحب.' },
          { title: 'الخروج من الشراكة — تسوية شاملة ومحكمة', desc: 'شروط الخروج: لا يمكن إخراج آخر شريك. مجموع الحصص يجب أن يكون ١٠٠٪ بالضبط. احسب: اختار تضمين الأصول الثابتة أم لا، ونسبة تسييل المخزون — الـ Payout يُحسَب لحظياً. ادفع من الخزينة أو أنشئ مديونية بتاريخ.' },
          { title: 'إغلاق الفترة المالية — نقطة البداية الجديدة', desc: 'بعد التحقق من أن الحصص = ١٠٠٪: تُؤرشَف بيانات الفترة بـ Net Equity كـ Opening Capital للفترة التالية. مستحقات الشركاء تتحول لـ Debts في الوحدة الخاصة بها. بداية نظيفة لكل فترة مالية جديدة.' },
        ],
      },
    ],
  },
  faq: {
    title: <>كل رقم مصدره <span style={{ color: '#8b5cf6' }}>صيغة واضحة.</span></>,
    subtitle: '',
    items: [
      { q: 'ما الفرق بين Net Profit وDistribution Base؟', a: 'Net Profit = Total Revenue - Total All Expenses (كل المصروفات بما فيها شراء البضاعة والشحن). هذا المؤشر يعكس صحة الأعمال الإجمالية. Distribution Base = Adjusted Net Equity - Effective Capital (رأس مال الشركاء + الإيداعات - السحوبات). هذا هو ما يُوزَّع فعلياً على الشركاء — قد يختلف عن Net Profit لأنه يأخذ في الاعتبار الأصول المادية والالتزامات القائمة.' },
      { q: 'كيف تُحسَب COGS في Financial Settlement؟', a: 'COGS = SUM(CostAtSale) من OrderItems مرتبطة بالطلبات غير الملغاة في الفترة المحددة. يُستخدَم JOIN مباشر على Orders ثم OrderItems في استعلام SQL واحد — لا round-trip "جلب IDs ثم جلب بنود". North star: CostAtSale هو سعر التكلفة وقت البيع (snapshot تاريخي) ليعكس الواقع الذي بِيع فيه المنتج.' },
      { q: 'لماذا لا تظهر بعض المصروفات في Burn Rate؟', a: 'Burn Rate يمثل OPEX التشغيلي الحقيقي المتكرر. تُستبعد منه: Ads (تختلف شهرياً وغير متكررة)، Goods Purchase (تكلفة بضاعة لا مصروف تشغيل)، Restock، Shipping (تكلفة منتجية لا ثابتة). هذا يعطي مؤشراً أنقى لمعدل "الحرق" الشهري للمصاريف الثابتة.' },
      { q: 'ما هو Implied Delivery Rate ولماذا يهم؟', a: 'Implied Delivery Rate = نسبة الطلبات المُسلَّمة فعلياً من إجمالي الطلبات التي دخلت في مرحلة الشحن — مشتقة من بياناتك الحقيقية. النظام يملأ بها سلايدر المحاكاة تلقائياً. هذا يجعل سيناريو "ماذا لو؟" منطلقاً من واقعك لا من افتراض ١٠٠٪.' },
      { q: 'كيف الفرق بين "Ship All Pipeline" و"Ship Ready Only" في المحاكاة؟', a: '"Ship All": يفترض شحن كل الطلبات في الـ Pipeline (بما فيها ذات الstockشورتيج) — يضاف RestockCost كالتزام إضافي. "Ship Ready Only": يُحسَب فقط من الطلبات التي لديها كل منتجاتها متوفرة في المخزون (بدون نقص). الفرق في Simulated Equity يكشف تأثير الطلبات المعلَّقة بنقص المخزون.' },
      { q: 'ما قيود الاستيراد إلى Excel؟', a: 'Full Orders: Max 180 يوم (لتفادي استعلامات ضخمة). Shipping Performance: Max 366 يوم. Products وInventory Valuation: بدون حد زمني (snapshot حالي). كلها تعيد XLSX باستخدام ClosedXML مع AdjustToContents() — الأعمدة تتسع تلقائياً على المحتوى.' },
      { q: 'كيف يعمل قسم Explainable BI في تقرير PDF؟', a: 'كل KPI يُخزَّن مع kpiBreakdowns: dictionary JSON بمكوناته. مثال: Net Equity = {assets: 250000, liabilities: 78000, result: 172000}. تقرير PDF يُظهر هذه المكونات في "KPI Explain Section" — المدير يرى الصيغة، المكونات، والنتيجة. لا أرقام معلَّقة بدون مرجع.' },
      { q: 'هل يمكن تغيير نسبة الشريك بعد إضافته؟', a: 'نعم — من خلال Edit Partner: غيِّر الاسم أو الحصة %. رأس المال المبدئي (InitialCapital) لا يمكن تغييره من Edit بل فقط بإضافة معاملة "Capital Increase" — هذا تعمُّدي لحفظ سجل التاريخ المالي الدقيق.' },
      { q: 'ما الذي يحدث بعد إغلاق الفترة المالية؟', a: 'يُسجَّل Net Equity الحالي كـ OpeningCapital للفترة الجديدة في جدول FinancialPeriods. مستحقات الشركاء من الأرباح تنتقل لوحدة المديونيات (Debts) كسجل رسمي. الشركاء يبدؤون الفترة الجديدة بسجل نظيف — الأرصدة المتراكمة لا تختفي بل تُحسَب في Opening Capital.' },
    ],
  },
  related: {
    layout: 'modern',
    title: <>التقارير <span style={{ color: '#8b5cf6' }}>تجمع كل وحداتك في ميزانية واحدة</span></>,
    items: [
      { to: '/features/dashboard', icon: LayoutDashboard, title: 'لوحة القيادة', body: 'التقارير تُغذِّي بيانات لوحة القيادة — المؤشرات اليومية تستمد أعدادها من نفس بنية الحسابات.' },
      { to: '/features/expenses', icon: Wallet, title: 'المصروفات والخزينة', body: 'Cash في الميزانية = SUM(Income) - SUM(Expenses) من وحدة المصروفات. Burn Rate مستمد مباشرةً من تصنيفات المصروفات.' },
      { to: '/features/inventory', icon: Boxes, title: 'إدارة المخزون', body: 'Inventory Value = CurrentStock × CostPrice للمتغيرات. Restock Cost = (ReservedStock - CurrentStock) × CostPrice. كلاهما خط أصول مباشر في الميزانية.' },
      { to: '/features/debts', icon: Landmark, title: 'المديونيات', body: 'Manual Receivables وPayables تأتي من ExternalDebts. عند إغلاق الفترة، مستحقات الشركاء تنتقل هنا كـ Debts رسمية.' },
      { to: '/features/shipping', icon: Truck, title: 'الشحن', body: 'In-Shipping value في الميزانية = قيمة الطلبات المشحونة النشطة. تقرير Shipping Performance Excel يُعطي أداء كل شركة خلال الفترة.' },
      { to: '/features/manufacturing', icon: Settings, title: 'التصنيع', body: 'FixedAssets من التصنيع تظهر مباشرةً في قسم الأصول في الميزانية وتؤثر على Net Equity وWorking Capital.' },
    ],
  },
  cta: {
    layout: 'modern',
    icon: FileText,
    eyebrow: 'ابدأ الآن',
    title: <>هل تعرف <span style={{ color: '#8b5cf6' }}>هامش ربحك الحقيقي</span><br />لهذا الشهر؟</>,
    description: 'لا تنتظر المحاسب. لا تجمع إكسيل. حوِّل بيانات متجرك إلى ميزانية حقيقية، تقرير CFO كامل، وسيناريوهات مستقبلية — في نقرة واحدة.',
    primaryLabel: 'ابدأ الآن مجاناً',
    secondaryLabel: 'استعرض الوحدات',
    secondaryToFeatures: true,
    trustBadges: [
      { icon: CheckCircle2, text: 'بدون بطاقة ائتمانية' },
      { icon: CheckCircle2, text: 'إعداد في أقل من ٥ دقائق' },
      { icon: CheckCircle2, text: 'دعم فني كامل بالعربية' },
    ],
  },
}
