import type { ModulePageConfig } from '../../types/module'
import {
  AlertTriangle,
  BarChart3,
  Bell,
  Building2,
  CheckCircle2,
  ClipboardList,
  Cloud,
  Database,
  EyeOff,
  HardDrive,
  History,
  KeyRound,
  RefreshCcw,
  Search,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  UserCog,
  Users,
} from 'lucide-react'

export const settingsModuleConfig: ModulePageConfig = {
  layout: 'modern',
  theme: {
    rgba: 'rgba(14,165,233,',
    hex: '#0ea5e9',
    dim: 'rgba(14,165,233,0.12)',
    dark: '#0284c7',
    glow: '0 0 28px rgba(14,165,233,0.40)',
    linkHoverClass: 'hover:text-sky-400',
    relatedHoverBorderClass: 'hover:border-sky-500/40',
    relatedHoverTextClass: 'group-hover:text-sky-400',
  },
  back: {
    label: 'العودة إلى جميع الوحدات',
    linkToFeatures: true,
  },
  hero: {
    badgeIcon: Settings,
    badgeLabel: 'الإعدادات والصلاحيات',
    title: <>سيطرة كاملة على <span style={{ color: '#0ea5e9' }}>من يرى ماذا — ومن يقدر يعمل إيه.</span><br />صلاحيات دقيقة. <span className="text-ocean-400">عزل شركات. تدقيق كامل.</span></>,
    description: 'RBAC متعدد المستويات: Role + Module + Action. كل API محمي بـ JWT وRequirePermission. حماية ضد IDOR بين الشركات. Password Policy قوية + BCrypt. Audit Trail لأي تغيير حساس. هذا ليس مجرد شاشة إعدادات — هذه طبقة الحوكمة الكاملة للنظام.',
    microStatsPills: [
      { icon: Shield, label: 'Role + Module + Action' },
      { icon: Building2, label: 'Tenant Isolation' },
      { icon: History, label: 'Audit Logs من JWT' },
    ],
    primaryCtaLabel: 'ابدأ الآن مجاناً',
    secondaryCtaLabel: 'اكتشف كل الوحدات',
    secondaryCtaToFeatures: true,
    image: {
    src: './assets/set-1-hero.png',
    alt: 'لوحة الإعدادات والصلاحيات — إدارة المستخدمين والأمان والنسخ الاحتياطي',
    width: 780,
    height: 480,
    loading: 'eager',
  },
    imageAnimation: 'modern',
  },
  pain: {
    stats: [
      { icon: ShieldAlert, value: 'صلاحيات عامة', label: 'لو كل الموظفين "Admin" في الواقع، فأنت لا تملك نظاماً — أنت تملك مخاطرة. أي موظف قد يصل لتقارير حساسة أو يمسح بيانات بلا قصد. هنا كل إجراء مرتبط بصلاحية محددة: view/create/edit/delete/admin/settle/closeDay.' },
      { icon: Building2, value: 'شركة واحدة؟', label: 'في SaaS متعدد الشركات، أخطر سيناريو هو IDOR: موظف من شركة A يصل لبيانات شركة B بتغيير companyId فقط. هنا كل endpoint حساس يمر على RequireCompanyMatchAsync — الطلب يُرفض فوراً لو الشركة لا تطابق التوكن.' },
      { icon: History, value: 'مين غيّر إيه؟', label: 'بدون Audit Trail لا يمكنك التحقيق في أي خرق. هنا سجل تدقيق كامل مع UserId وUsername مأخوذين من JWT claims، وليس من بيانات مرسلة من العميل. تعرف من غيّر ومتى ولماذا.' },
    ],
  },
  value: {
    sectionLabel: 'لماذا الإعدادات عندنا مختلفة؟',
    title: 'لأن الأمان ليس "زر" — إنه بنية كاملة على مستوى الكود.',
    subtitle: 'من السياسة الصارمة لكلمات المرور إلى عزل التينانتات، ومن سجل تدقيق موثوق إلى تحكم دقيق بكل إجراء لكل وحدة. هذه الصفحة تجمع كل أدوات الحوكمة والإدارة التي يحتاجها أي SaaS جاد.',
    cards: [
      { icon: Shield, title: 'RBAC فعلي: Role + Module + Action', desc: 'النظام لا يعتمد على "Role" فقط. كل endpoint يمكن حمايته بـ [RequirePermission("Module", "action")]. الصلاحيات الدقيقة تأتي من PermissionsJson (module -> actions). عند غيابها: fallback على AllowedModules legacy لضمان التوافق العكسي.', color: '' },
      { icon: KeyRound, title: 'Password Policy + BCrypt = أمان حقيقي', desc: 'كلمة المرور الجديدة يجب أن تحتوي: ٨ أحرف كحد أدنى + حرف كبير + صغير + رقم + رمز خاص. التخزين مشفر BCrypt workFactor=12، وليس hash بسيط. الحسابات القديمة لها مسار ترقية أثناء تسجيل الدخول.', color: '' },
      { icon: Building2, title: 'Tenant Isolation ضد IDOR', desc: 'كل عمليات حساسة في Settings تمر عبر RequireCompanyMatchAsync. أي companyId لا يطابق tenant في JWT يُرفض فوراً. حتى تحديث/حذف مستخدم لديه guard إضافي (CompanyId must match tenant). بيانات الشركات معزولة فعلياً.', color: '' },
      { icon: UserCog, title: 'AppUser منفصل عن Employee', desc: 'تصميم Decoupled IAM: بيانات الدخول والصلاحيات في AppUser، وبيانات HR/Payroll في Employee. الربط اختياري عبر EmployeeId. نفس الموظف يمكن ربطه بحساب واحد فقط (unique). أو يمكنك إنشاء حساب إداري بدون أي سجل رواتب.', color: '' },
      { icon: Users, title: 'Roles قابلة للتعيين بأمان', desc: 'Tenant admin لا يستطيع إنشاء SuperAdmin. الأدوار المسموحة: Admin, Manager, Moderator, Marketer, Staff فقط. أي Role خارج القائمة مرفوض فوراً مع رسالة واضحة. يقلل التصعيد غير المقصود للصلاحيات.', color: '' },
      { icon: EyeOff, title: 'Deactivate user = سحب الوصول فوراً', desc: 'حذف المستخدم هنا soft-delete ذكي: IsActive=0 + PasswordHash=null + AllowedModules=null + PermissionsJson=null. الحساب يبقى لأغراض التدقيق التاريخي، لكن لا يستطيع تسجيل الدخول إطلاقاً.', color: '' },
      { icon: History, title: 'Audit Logs موثوقة من JWT claims', desc: 'Endpoint audit/log يتجاهل userId/username القادم من العميل. يقرأهما مباشرة من ClaimTypes.NameIdentifier وClaimTypes.Name داخل JWT. هذا يمنع انتحال الهوية في سجلات التدقيق ويجعل كل أثر موثوقاً قانونياً.', color: '' },
      { icon: Cloud, title: 'Cloud Sync & Smart Archive', desc: 'الإعدادات ليست أمان فقط. لديك smart archive لنقل الطلبات النهائية الأقدم من N يوم إلى الأرشيف، مع دعم مزامنة بيانات النظام. هذا يقلل ضغط الجداول الحية ويحسّن الأداء مع نمو البيانات.', color: '' },
      { icon: HardDrive, title: 'Backup & Restore بمسار آمن', desc: 'Export/Import CSV ZIP يتحقق من اسم الملف عبر ValidateExportFileName ويمنع directory traversal. فقط plain filename داخل ExportBaseDir. حماية قوية ضد استغلال paths الخبيثة.', color: '' },
      { icon: AlertTriangle, title: 'Danger Zone مع تحقق كلمة Admin', desc: 'عمليات مدمرة (clear orders, factory reset, replace table) تتطلب admin password. لا ضغطات خاطئة. يوجد مستويات reset منفصلة، ورسائل نجاح/فشل صريحة تساعدك تتصرف بسرعة وقت الطوارئ.', color: '' },
      { icon: BarChart3, title: 'Report Preferences مركزية', desc: 'سيناريوهات التقارير مثل default delivery rate وdefault scenario تُدار مركزياً من settings API. أي تغيير ينعكس على التقارير التشغيلية والمالية تلقائياً بدون تعديل يدوي في كل شاشة.', color: '' },
      { icon: RefreshCcw, title: 'Settings Cache + Invalidation ذكي', desc: 'إعدادات الشركة تُخزَّن في MemoryCache لمدة ٣٠ دقيقة لتسريع القراءة. عند أي تعديل: RemoveCompanySettingsCache يُفرغ الكاش فوراً. تجمع بين الأداء والدقة بدون stale values.', color: '' },
    ],
  },
  walkthrough: {
    sectionLabel: 'كيف تعمل المنظومة؟',
    title: 'من إنشاء الحساب إلى سياسة أمان قابلة للتدقيق',
    subtitle: '',
    tabs: [
      {
        id: 'users',
        label: 'المستخدمون والصلاحيات',
        icon: Users,
        imgSrc: './assets/set-2-list.png',
        imgAlt: 'إدارة المستخدمين والصلاحيات الدقيقة وربط المستخدم بالموظف',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: 'أنشئ مستخدماً وربطه بموظف HR (اختياري)', desc: 'عند إنشاء AppUser يمكنك اختيار EmployeeId لربط الحساب بسجل HR. يتحقق النظام أن الموظف موجود في نفس الشركة ولم يُربط بحساب آخر. هذا يضمن one-to-one link ويوحد الهوية عبر النظام.' },
          { title: 'اختر Role قابل للتعيين فقط', desc: 'الأدوار المسموحة للعميل: Admin/Manager/Moderator/Marketer/Staff. أي محاولة لتعيين SuperAdmin مرفوضة. للـ Admin: AllowedModules = "All" تلقائياً. لا حاجة لتكوين يدوي.' },
          { title: 'PermissionsJson أدق من AllowedModules', desc: 'إذا زودت permissions الدقيقة (مثلاً Sales: [view,create] وExpenses:[view]) يتم حفظها JSON وتصبح المرجع الأساسي في التحقق. AllowedModules يُشتق من مفاتيحها للتوافق مع الشاشات القديمة.' },
          { title: 'إلغاء مستخدم بدون فقدان التاريخ', desc: 'Delete لا يمسح السجل: يجمد الحساب (IsActive=0) ويلغي credentials والصلاحيات. يبقى للمراجعة التاريخية. لا يمكن حذف حساب admin الرئيسي ولا تعديل حالته — حماية من lockout الكارثي.' },
        ],
      },
      {
        id: 'security',
        label: 'الأمان متعدد الشركات',
        icon: ShieldCheck,
        imgSrc: './assets/set-3-action.png',
        imgAlt: 'حماية الأمان متعددة الشركات والتحقق من الصلاحيات',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: 'JWT + Claims كأساس كل قرار', desc: 'UserId وRole وTenantId مأخوذة من JWT. كل endpoint حساس يقرأ claims مباشرة. لا ثقة في قيم العميل المتغيرة. التوكن هو مصدر الحقيقة الوحيد للهوية والسياق.' },
          { title: 'RequireCompanyMatchAsync ضد IDOR', desc: 'قبل أي تعديل/قراءة tenant-scoped: مقارنة companyId المطلوب مع tenant في السياق. mismatch = رفض فوري. حتى لو المستخدم حاول تغيير companyId في query string، لا يمكنه القفز لبيانات شركة أخرى.' },
          { title: 'RequirePermission لكل Action حساس', desc: 'الفلتر يفحص: هل المستخدم Admin/SuperAdmin؟ إذا لا، يفحص PermissionsJson للفعل المطلوب داخل الوحدة. عند عدم وجود JSON: fallback AllowedModules. النتيجة: granular authorization مع backward compatibility.' },
          { title: 'IDOR Guard داخل الخدمة نفسها', desc: 'SettingsService يضيف guard ثانية: عند update/delete/toggle user يُطلب أن CompanyId للمستخدم = tenant الحالي. طبقة API + طبقة service معاً = دفاع متعدد الطبقات (defense in depth).' },
        ],
      },
      {
        id: 'backup',
        label: 'النسخ والبيانات',
        icon: Database,
        imgSrc: './assets/set-4-details.png',
        imgAlt: 'النسخ الاحتياطي والاستيراد والاستعادة ودنجر زون',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: 'Backup محلي + Restore', desc: 'إنشاء نسخة احتياطية محلية، تنزيل export كـ ZIP، واستعادة قاعدة البيانات من ملف backup. API يعيد رسائل واضحة success/failure لكل خطوة لسهولة تشغيل العمليات من الواجهة.' },
          { title: 'CSV ZIP Import/Export مع حماية Path', desc: 'قبل أي استيراد/تصدير CSV ZIP: ValidateExportFileName يتحقق أن الاسم plain filename وأن المسار النهائي داخل ExportBaseDir. يحبط أي directory traversal مثل ../../secret.db.' },
          { title: 'Auto Backup Settings', desc: 'تفعيل النسخ الدوري (daily/weekly) مع max count. عند التخطي: حذف أقدم النسخ تلقائياً. لديك endpoint run-if-due لتشغيل النسخ تلقائياً عند فتح النظام وقت الاستحقاق.' },
          { title: 'Danger Zone بمستويين Reset', desc: 'Level-based factory reset مع admin password. يوجد clear-orders منفصل، وreplace-table، وfactory reset. كل عملية مدمرة تمر بتحقق واضح ورسائل جلية تمنع أخطاء التشغيل.' },
        ],
      },
      {
        id: 'ops',
        label: 'العمليات والمراقبة',
        icon: ClipboardList,
        imgSrc: './assets/set-5-extras.png',
        imgAlt: 'الإعدادات التشغيلية وتدقيق العمليات وسجل الأمان',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: 'Company Profile مركزي', desc: 'تحديث بيانات الشركة (Name/Phone/Address/Tax/Currency) من endpoint واحد. تستخدم عبر النظام في الوثائق والتقارير والطباعة. لا تكرار يدوي للإعدادات في أكثر من مكان.' },
          { title: 'Report Preferences متقدمة', desc: 'تحديد default scenario وdelivery rate وliquidation% من settings APIs. هذا يضمن أن تحليلات الفرق المختلفة متسقة، ولا تختلف النتائج بسبب default مختلف لكل مستخدم.' },
          { title: 'Smart Archive لتحسين الأداء', desc: 'نقل الطلبات النهائية الأقدم من N يوم من الجداول الحية إلى الأرشيف (copy ثم delete). قاعدة بيانات أخف، صفحات أسرع، وتقارير تاريخية ما زالت متاحة في الأرشيف.' },
          { title: 'Audit & Forensics جاهزة', desc: 'استعلام audit logs بفلترة user/action/date مع pagination (limit/offset). عند حادث أمني أو حذف غير مصرح: تصل للحقيقة خلال دقائق، لا ساعات. الحوكمة الفعلية تعتمد على أثر رقمي موثوق.' },
        ],
      },
    ],
  },
  faq: {
    title: <>أمان قابل للتدقيق — <span style={{ color: '#0ea5e9' }}>بأدلة من الكود نفسه.</span></>,
    subtitle: '',
    items: [
      { q: 'كيف تتأكدون أن مستخدم شركة ما لا يصل لبيانات شركة أخرى؟', a: 'هناك حماية مزدوجة. في الـ Controller: RequireCompanyMatchAsync يتحقق أن companyId في الطلب يساوي tenant من JWT. في الـ Service: update/delete/toggle للمستخدمين فيها IDOR guard يفرض CompanyId == tenant. أي mismatch يُرفض قبل تنفيذ أي عملية.' },
      { q: 'هل AllowedModules وحده كافٍ للأمان؟', a: 'AllowedModules هو fallback legacy فقط. المسار الحديث هو PermissionsJson: قاموس module -> actions مثل view/create/edit/delete/admin/settle/closeDay. RequirePermission يفحص JSON أولاً. إذا غير موجود يرجع للـ fallback لضمان عدم كسر الحسابات القديمة.' },
      { q: 'ما الذي يمنع انتحال الهوية في سجل التدقيق؟', a: 'Endpoint audit/log يتجاهل userId وusername المرسلين من الـ client ويستخرج الهوية من JWT claims مباشرة (NameIdentifier + Name). لا يمكن للواجهة أن تكتب log باسم شخص آخر حتى لو حاولت.' },
      { q: 'هل يمكن ربط نفس الموظف بأكثر من حساب مستخدم؟', a: 'لا. عند SaveUserAsync إذا تم تمرير EmployeeId، النظام يتحقق أن هذا الموظف غير مرتبط مسبقاً بأي AppUser آخر. لو مرتبط بالفعل، العملية تُرفض برسالة واضحة: employee already linked.' },
      { q: 'كيف تُحمى كلمات المرور؟', a: 'عند إنشاء أو تغيير كلمة المرور: PasswordPolicy يفرض 8+ أحرف مع upper/lower/digit/special. بعدها يتم hash بـ BCrypt workFactor=12 قبل التخزين. كلمة المرور الخام لا تُحفظ إطلاقاً.' },
      { q: 'ماذا يعني Delete user في النظام الحديث؟', a: 'Delete هو deactivation آمن: IsActive=0، PasswordHash=null، AllowedModules=null، PermissionsJson=null. يبقى السجل للـ audit ولا يستطيع المستخدم تسجيل الدخول. هذا يوفر تتبع تاريخي بدون مخاطر وصول.' },
      { q: 'كيف تمنعون ثغرات path traversal في الاستيراد/التصدير؟', a: 'أي اسم ملف يأتي من العميل يمر عبر ValidateExportFileName: يقبل plain filename فقط، ثم يبني المسار داخل ExportBaseDir ويتأكد أن path النهائي لا يخرج خارج المجلد المحدد. أي محاولة ../ أو مسارات مطلقة تُرفض بـ 400.' },
      { q: 'هل الإعدادات بطيئة عند كثرة القراءة؟', a: 'لا. GetSettingsAsync تستخدم MemoryCache لمدة 30 دقيقة لكل tenant. وعند أي تعديل SetSetting/SetSettingsMany يتم إزالة cache مباشرة RemoveCompanySettingsCache، فيعود النظام يقرأ القيم الأحدث بدون stale data.' },
    ],
  },
  related: {
    layout: 'modern',
    title: <>الإعدادات تحكم المنظومة كلها — <span style={{ color: '#0ea5e9' }}>وليس صفحة منفصلة</span></>,
    items: [
      { to: '/features/staff', icon: Users, title: 'فريق العمل والموارد البشرية', body: 'AppUser يمكن ربطه اختيارياً بـ EmployeeId. هذا يضمن أن هوية المستخدم وصلاحياته منفصلة عن بيانات الرواتب، مع رابط مرجعي دقيق بين الأمن والـ HR.' },
      { to: '/features/reports', icon: BarChart3, title: 'التقارير', body: 'تفضيلات التقارير الافتراضية (scenario/delivery-rate/liquidation) تُدار من Settings. التقارير تستخدم هذه القيم تلقائياً لضمان اتساق القراءة المالية بين الفرق.' },
      { to: '/features/expenses', icon: Database, title: 'المصروفات والخزينة', body: 'Danger Zone وعمليات reset تؤثر على جداول المعاملات المالية. وجود صلاحيات دقيقة على Settings يحميك من مسح مصروفات أو قيود خزينة عن طريق الخطأ.' },
      { to: '/features/dashboard', icon: Search, title: 'لوحة القيادة', body: 'التحكم الدقيق في view/create/edit يحدد من يستطيع رؤية مؤشرات الأداء العامة في الـ Dashboard. الموظف يرى فقط ما يحتاجه لعمله — لا أكثر.' },
      { to: '/features/ads', icon: Bell, title: 'الإعلانات', body: 'صلاحيات Ads (مثل settle أو edit) تُدار من نفس محرك RBAC في Settings. يمكنك السماح للماركيتر بقراءة الأداء فقط دون تعديل الحملات أو المصروفات.' },
      { to: '/features/debts', icon: AlertTriangle, title: 'الديون والمستحقات', body: 'بيانات الديون شديدة الحساسية. بفضل permissions الدقيقة، يمكن للمحاسبة الوصول الكامل بينما فريق التشغيل يمتلك view فقط أو لا يمتلك وصولاً أصلاً.' },
    ],
  },
  cta: {
    layout: 'modern',
    icon: Settings,
    eyebrow: 'ابدأ الآن',
    title: <>جاهز تبني نظام <span style={{ color: '#0ea5e9' }}>يضمن لك السيطرة الكاملة؟</span></>,
    description: 'موظف يرى ما يحتاجه فقط. مدير يغيّر ما يملكه فقط. وكل إجراء حساس مسجل ويمكن مراجعته. بإعدادات Maly OBS، الأمان ليس وعد تسويقي — هو سلوك مُنفَّذ داخل كل API.',
    primaryLabel: 'ابدأ الآن مجاناً',
    secondaryLabel: 'استعرض الوحدات',
    secondaryToFeatures: true,
    trustBadges: [
      { icon: CheckCircle2, text: 'RBAC دقيق لكل إجراء' },
      { icon: CheckCircle2, text: 'عزل شركات متعدد المستأجرين' },
      { icon: CheckCircle2, text: 'سجل تدقيق كامل وموثوق' },
    ],
  },
}
