import type { ModulePageConfig } from '../../types/module'
import {
  ArrowRightLeft,
  BadgeDollarSign,
  Banknote,
  BarChart3,
  Calculator,
  CheckCircle2,
  ClipboardList,
  Coins,
  FileText,
  History,
  LayoutDashboard,
  Lock,
  Megaphone,
  Repeat,
  Settings,
  ShieldCheck,
  TimerReset,
  TrendingUp,
  UserCheck,
  Users,
  Wallet,
} from 'lucide-react'

export const staffModuleConfig: ModulePageConfig = {
  layout: 'modern',
  theme: {
    rgba: 'rgba(168,85,247,',
    hex: '#a855f7',
    dim: 'rgba(168,85,247,0.12)',
    dark: '#9333ea',
    glow: '0 0 28px rgba(168,85,247,0.40)',
    linkHoverClass: 'hover:text-purple-400',
    relatedHoverBorderClass: 'hover:border-purple-500/40',
    relatedHoverTextClass: 'group-hover:text-purple-400',
  },
  back: {
    label: 'العودة إلى جميع الوحدات',
    linkToFeatures: true,
  },
  hero: {
    badgeIcon: Users,
    badgeLabel: 'فريق العمل والموارد البشرية',
    title: <>إدارة رواتب فريقك <span style={{ color: '#a855f7' }}>بدقة محاسبية.</span><br />بدون إكسيل — <span className="text-ocean-400">بدون مفاجآت.</span></>,
    description: '٥ طرق راتب مختلفة. حساب عمولة مودريتور ومنيجر وماركيتر من طلباتك الحقيقية. سُلَف مع تأمين خزينة بـ PostgreSQL Row Lock. رواتب تُحسَب server-side — محمية من أي تلاعب. كل دفعة تُنشئ مصروفاً محاسبياً تلقائياً.',
    microStatsPills: [
      { icon: BadgeDollarSign, label: '٥ طرق راتب' },
      { icon: TrendingUp, label: 'حساب عمولة من الطلبات' },
      { icon: Lock, label: 'سُلَف محمية بـ Row Lock' },
    ],
    primaryCtaLabel: 'ابدأ الآن مجاناً',
    secondaryCtaLabel: 'اكتشف كل الوحدات',
    secondaryCtaToFeatures: true,
    image: {
    src: './assets/stf-1-hero.png',
    alt: 'لوحة إدارة الرواتب والموارد البشرية — كشف رواتب وعمولات وسلف',
    width: 780,
    height: 480,
    loading: 'eager',
  },
    imageAnimation: 'modern',
  },
  pain: {
    stats: [
      { icon: ClipboardList, value: 'إكسيل', label: 'كشف الرواتب في إكسيل يعني: أخطاء في الصيغ، نسيان السُّلَف في آخر الشهر، عمولات محسوبة على طلبات لم تُسلَّم. هنا المحرك يحسب كل شيء من طلباتك الحقيقية — لا إدخال يدوي في الصيغ.' },
      { icon: Coins, value: 'سلفة', label: 'سلفة لموظف بدون سجل رسمي = نقاش في آخر الشهر. هنا: كل سلفة تُسجَّل كمصروف محاسبي تلقائياً، تُخصَم من الراتب القادم، ومحمية بـ Row-Level Lock في قاعدة البيانات — يستحيل خصم نفس المبلغ مرتين.' },
      { icon: Users, value: 'موديراتور', label: 'حساب عمولة موديراتور أو منيجر يدوياً من جداول الطلبات يأخذ ساعات — وغالباً ينتهي بنقاش. هنا: العمولة تأتي من الأرشيف مباشرةً — طلبات مُسلَّمة فقط (أو الكل بخيارك) — وتُحسَب ثانياً server-side عند الدفع.' },
    ],
  },
  value: {
    sectionLabel: 'لماذا HR متكامل؟',
    title: 'الرواتب ليست إكسيل — هي التزام مالي بدقة محاسبية.',
    subtitle: 'من حساب العمولة على الطلبات المُسلَّمة فعلاً، إلى تأمين السُّلَف بـ Row Lock في قاعدة البيانات، إلى كشف الراتب المُعاد حسابه server-side عند كل دفعة — وحدة HR مبنية على معايير مالية حقيقية لا على قوائم بسيطة.',
    cards: [
      { icon: BadgeDollarSign, title: '٥ طرق راتب — لكل دور نموذجه', desc: 'Fixed (ثابت)، Fixed+Commission% (ثابت + نسبة من المبيعات)، Fixed+PerOrder (ثابت + مبلغ لكل طلب)، Fixed+PerItem (ثابت + مبلغ لكل قطعة)، Percentage (نسبة من إنفاق الإعلانات للماركيتر). كل طريقة تُحسَب تلقائياً من بيانات الطلبات الحقيقية.', color: '' },
      { icon: TrendingUp, title: 'عمولة من الأرشيف — لا إدخال يدوي', desc: 'المودريتور: عمولته من الطلبات التي يحمل اسمه. المنيجر: عمولته من طلبات مودريتوراته المرتبطين به. CommissionScope: "Delivered Only" أو "All Orders". الطلبات تُجلَب من الأرشيف بعد استبعاد المُسوَّاة لمنع العد المزدوج.', color: '' },
      { icon: ShieldCheck, title: 'Server-Side Recalculation — محمي من التلاعب', desc: 'عند الدفع: النظام يحسب الراتب من جديد server-side — لا يعتمد على الأرقام المُرسَلة من الـ client. إذا كان PayAmount > NetDue المحسوب server-side بفارق ٠.٠١: طلب مرفوض بـ 400 مع رسالة واضحة. مستحيل دفع أكثر من المستحق.', color: '' },
      { icon: Lock, title: 'Row-Level Lock للسُّلَف — لا تكرار', desc: 'عند تسجيل سلفة: يُقفَل صف الخزينة (SELECT FOR UPDATE) + صف الموظف — يمنع سحب نفس المبلغ مرتين في حالة طلبين متزامنين. يُفحَص رصيد الخزينة بعد القفل. الموظف يُعاد تحميله لضمان CurrentBalance الحديث.', color: '' },
      { icon: Banknote, title: 'كل دفعة = مصروف محاسبي تلقائي', desc: 'عند معالجة الراتب: يُنشأ Expense (Category: "Salaries", is_auto=1) تلقائياً في جدول المصروفات. السلفة تُنشئ Expense (Category: "Staff Loans", is_auto=1). كلتاهما محميتان من التعديل. تؤثران على Burn Rate والخزينة فوراً.', color: '' },
      { icon: Repeat, title: 'Carried Over — لا رصيد يضيع', desc: 'دفعت جزءاً من الراتب؟ ما تبقى يُحفَظ كـ CarriedOverBalance ويُضاف تلقائياً لكشف الراتب القادم. دفعت أكثر (سُلفة)؟ يُحفَظ كـ CurrentBalance سالب ويُطرح من الراتب القادم. النظام يتتبع كل فلس.', color: '' },
      { icon: TimerReset, title: 'Proration — راتب يومي بالأيام الفعلية', desc: 'الراتب الأساسي المستحق = BaseSalary × (أيام العمل ÷ أيام الشهر). إذا كان الفارق ≤ ٢ يوم يُعامَل كشهر كامل — تجنباً للفروق في نهاية الشهر. الحساب server-side بناءً على LastPaidDate الفعلية.', color: '' },
      { icon: Users, title: 'هيكل إداري — منيجر → موديراتور', desc: 'كل مودريتور مرتبط بمنيجر. المنيجر يستطيع تتبع مودريتوراته. عمولة المنيجر تُحسَب من مجموع طلبات كل مودريتوراته مجتمعةً. الهرم يظهر في لوحة الفريق ويؤثر مباشرةً على حساب العمولات.', color: '' },
      { icon: ArrowRightLeft, title: 'حذف مع ترحيل للديون — لا رصيد يختفي', desc: 'عند حذف موظف برصيد مستحق: يُنشأ Debt تلقائياً في وحدة الديون (Payable لو النظام يدين الموظف — Receivable لو الموظف يدين الشركة). الموظف يصبح IsActive=0 (Soft Delete) ولا يختفي من السجل التاريخي.', color: '' },
      { icon: UserCheck, title: 'موظف ≠ مستخدم — فصل كامل', desc: 'EmployeeInputDto: بيانات HR فقط (Name, Role, SalaryMethod, BaseSalary…). لا Username، لا Password. الصلاحيات تُدار حصراً في وحدة الإعدادات على AppUser. يمكن أن يكون للموظف حساب مرتبط — أو لا. استقلالية تامة.', color: '' },
      { icon: History, title: 'سجل كامل لكل الحركات', desc: 'كل Bonus، Deduction، Loan، Salary Payment مُسجَّل في EmployeeTransactions مع تاريخ ودور وملاحظات. قابل للفلترة بالموظف أو الدور. SalaryAdjustments تُرفع تلقائياً (IsApplied=1) في نفس transaction الدفع — تراجع أكثر أمناً.', color: '' },
      { icon: BarChart3, title: 'لوحة HR — ٧ KPIs بنظرة واحدة', desc: 'إجمالي الموظفين + توزيع الأدوار، LifetimePaid (إجمالي ما دُفع تاريخياً)، MonthPaid (هذا الشهر)، DueToday (المستحق اليوم عبر proration)، PendingBalance (أرصدة محمولة معلقة). كلها تُحسَب في PostgreSQL — لا loops جانب الـ API.', color: '' },
    ],
  },
  walkthrough: {
    sectionLabel: 'كيف يعمل؟',
    title: 'من تسجيل الموظف إلى دفع الراتب بقيد محاسبي',
    subtitle: '',
    tabs: [
      {
        id: 'team',
        label: 'إدارة الفريق',
        icon: Users,
        imgSrc: './assets/stf-2-list.png',
        imgAlt: 'جدول الفريق — أدوار ومرتبات وحالة كل موظف',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: 'أضف موظفاً: الدور + طريقة الراتب', desc: 'اختر الدور: Manager / Moderator / Staff / Accountant / Marketer. اختر طريقة الراتب الأنسب. للمودريتور: حدِّد منيجره. للماركيتر بـ Percentage: أدخل إنفاق الإعلانات. JoiningDate وLastPaidDate إلزاميان ولا يتغيران بعد الحفظ — قاعدة مراجعة HR.' },
          { title: 'CommissionScope — أي الطلبات تُحسَب؟', desc: '"Delivered Only": العمولة فقط على الطلبات المُسلَّمة — حماية من العمولات على المرتجعات. "All Orders": العمولة على كل الطلبات بغض النظر عن الحالة. الخيار يؤثر مباشرةً على حساب العمولة في كشف الراتب.' },
          { title: 'تعديل الموظف — البيانات القابلة للتغيير', desc: 'يمكن تغيير: الاسم، الدور، طريقة الراتب، الراتب الأساسي، العمولة، المنيجر، AdSpend، CommissionScope. لا يمكن تغيير: JoiningDate وLastPaidDate — محميان بـ HR audit rule في الـ backend.' },
          { title: 'Soft Delete مع حماية الرصيد', desc: 'حذف موظف برصيد → يُنشأ Debt في وحدة الديون تلقائياً (Payable أو Receivable حسب اتجاه الرصيد) ثم يُضبَط IsActive=0. الموظف بدون رصيد → Soft Delete بصمت. في الحالتين: السجل التاريخي محفوظ ولا حذف فعلي من قاعدة البيانات.' },
        ],
      },
      {
        id: 'payroll',
        label: 'كشف الراتب',
        icon: Calculator,
        imgSrc: './assets/stf-3-action.png',
        imgAlt: 'كشف الراتب — تفصيل المكسب والاستقطاعات والمبلغ المستحق',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: 'احسب الراتب — PeriodFrom تلقائياً', desc: 'PeriodFrom = LastPaidDate + يوم واحد (أو أول الشهر إن لم يُدفَع بعد). حدِّد PeriodTo واضغط "Calculate". الكشف يظهر: Carried Over + Accrued Base (بالأيام) + Commission + Bonus - Deductions - Loans = Net Due.' },
          { title: 'Proration — حساب الأيام الفعلية', desc: 'AccruedSalary = BaseSalary × (daysWorked ÷ daysInMonth). إذا كان الفارق بين daysWorked وdaysInMonth ≤ ٢ يوم: multiplier = 1.0 (شهر كامل). منع الاستقطاعات التلقائية لأيام نهاية الشهر القليلة.' },
          { title: 'Commission من الأرشيف — لا إدخال يدوي', desc: 'المودريتور: يجلب ArchivedOrders حيث moderator_name = اسم الموظف + ModeratorSettled=0. المنيجر: يجلب طلبات مودريتوراته مع IsManagerPaid=0. بعد الدفع: تُصفَّر (ModeratorSettled/IsManagerPaid=1) لمنع الاحتساب المزدوج في الشهر القادم.' },
          { title: 'Process Payment — Server Recalculates', desc: 'عند الدفع: الـ server يعيد حساب الكشف مستقلاً (BuildPayrollBreakdownAsync). إذا PayAmount > NetDue+0.01: مرفوض. إذا PayAmount < NetDue: الباقي يُحفَظ CarriedOverBalance. يُنشأ EmployeeTransaction + Expense (Salaries, is_auto=1) في نفس DB transaction.' },
        ],
      },
      {
        id: 'adjustments',
        label: 'مكافآت وسلف',
        icon: Coins,
        imgSrc: './assets/stf-4-details.png',
        imgAlt: 'مكافآت واستقطاعات وسلف — إدارة التعديلات على الراتب',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: 'Bonus — مكافأة فورية بسجل محاسبي', desc: 'أدخل المبلغ والسبب. يُحفَظ في SalaryAdjustments (Type=Bonus, IsApplied=0). عند حساب الراتب يُضاف للـ Gross. عند الدفع: يُرفَع تلقائياً (IsApplied=1) في نفس transaction الدفع — لا مكافأة تُحسَب مرتين.' },
          { title: 'Deduction — استقطاع بسبب واضح', desc: 'نفس آلية المكافأة: يُحفَظ بـ IsApplied=0 وعند الدفع يُضبَط IsApplied=1 أتوماتيكياً. يُطرح من الـ Gross في كشف الراتب. السبب إلزامي للوضوح المحاسبي.' },
          { title: 'Loan — سُلفة مع تأمين مزدوج', desc: 'السلفة تُدفَع من الخزينة فوراً — يُقفَل صف الخزينة (SELECT treasury FOR UPDATE) + صف الموظف (SELECT employee FOR UPDATE) قبل أي عملية. CurrentBalance يتناقص بمقدار السلفة. يُنشأ EmployeeTransaction (Loan سلفة) + Expense (Staff Loans, is_auto=1).' },
          { title: 'متى تُخصَم السلفة من الراتب؟', desc: 'CurrentBalance السالب = سلفة غير مُسدَّدة. في الكشف: Loans = Abs(CurrentBalance < 0). تُطرح من إجمالي الراتب تلقائياً. لا تحتاج لإدخال يدوي — النظام يعرف ما تبقى ويطرحه في الدورة التالية دون تدخل.' },
        ],
      },
      {
        id: 'history',
        label: 'السجل والإحصاء',
        icon: History,
        imgSrc: './assets/stf-5-extras.png',
        imgAlt: 'سجل المعاملات ولوحة HR KPIs',
        imgW: 880,
        imgH: 540,
        steps: [
          { title: 'Dashboard KPIs — ٧ مؤشرات HR', desc: 'TotalEmployees (حسب الدور)، LifetimePaid (مجموع كل المدفوعات تاريخياً من EmployeeTransactions)، MonthPaid (هذا الشهر)، DueToday (مستحق اليوم بالـ proration لكل موظف active)، PendingBalance (مجموع CarriedOverBalance + CurrentBalance الإيجابي).' },
          { title: 'DueToday — حساب تراكمي يومي', desc: 'لكل موظف: DueToday = (أيام من LastPaidDate لليوم ÷ أيام الشهر) × BaseSalary + CarriedOver + Commission المتراكمة + Bonus - Deduction. ComputePayrollNetDueBatchAsync يحسب الجميع دفعةً واحدة في استعلامات SQL — لا loops جانب الـ API.' },
          { title: 'History Table — سجل بكل حركة', desc: 'كل Bonus, Deduction, Loan (سلفة), Salary Payment مسجَّلة بـ: التاريخ، الموظف، الدور، النوع، المبلغ، الملاحظات. فلترة بالدور أو الموظف المحدَّد. حد 100 سجل افتراضياً — قابل للتخصيص.' },
          { title: 'Optimistic Concurrency — آمن للفريق', desc: 'Employee.Version مربوط بـ xmin في PostgreSQL (System Concurrency Column). أي تحديثين متزامنين على نفس الموظف: الثاني يفشل بـ DbUpdateConcurrencyException — يمنع الكتابة فوق نقل الرصيد. الـ API يُعيد 409 Conflict مع رسالة واضحة.' },
        ],
      },
    ],
  },
  faq: {
    title: <>رواتب بدقة محاسبية — <span style={{ color: '#a855f7' }}>لا تخمين ولا مفاجآت.</span></>,
    subtitle: '',
    items: [
      { q: 'هل حساب الراتب على الـ server يمنع التلاعب فعلاً؟', a: 'نعم — عند الضغط على "Process Payment": الـ server يستدعي BuildPayrollBreakdownAsync مستقلاً بالـ empId وPeriodTo. إذا كان الـ PayAmount المُرسَل أكبر من NetDue المحسوب server-side بفارق أكثر من ٠.٠١: يُرفَض الطلب بـ InvalidOperationException مع رسالة: "Refresh the payslip and try again". الـ server لا يثق في أي رقم من الـ client.' },
      { q: 'كيف تمنع السُّلَف المتزامنة خصم نفس المبلغ مرتين؟', a: 'قبل أي عملية سُلفة: يُقفَل صف الخزينة (SELECT FROM treasury WHERE CompanyId={0} FOR UPDATE) ثم صف الموظف (SELECT FROM employees WHERE Id={0} FOR UPDATE). هذان القفلان يُسلسِلان الطلبات المتزامنة — لا طلبان قادران على اجتياز هذه النقطة في آنٍ واحد. بعد القفل يُعاد تحميل CurrentBalance بـ Entry.ReloadAsync.' },
      { q: 'ما الفرق بين CurrentBalance وCarriedOverBalance؟', a: 'CurrentBalance: الرصيد السائل للموظف. إن كان سالباً: سلفة غير مُسدَّدة تُخصَم في الدورة القادمة. CarriedOverBalance: فائض من دفعة جزئية (دفعت أقل من NetDue) — يُضاف للـ Gross Earnings في الكشف القادم. كلاهما يُتتَبع منفصلاً ليكون الكشف واضحاً: ما هو محمول وما هو سلفة.' },
      { q: 'ما الفرق بين موظف HR وحساب النظام؟', a: 'الموظف HR مُعرَّف في جدول Employees: اسم، دور وظيفي، طريقة راتب — بدون أي بيانات مصادقة. حساب النظام (AppUser) مُعرَّف منفصلاً في Settings ويحمل: Username، Password، Role، Permissions. الربط بين الاثنين اختياري (AppUser navigation property) — يمكن أن يكون لموظف HR حساب نظام أو لا.' },
      { q: 'كيف تعمل عمولة المنيجر؟', a: 'المنيجر: يجلب GetManagerOrdersForCommissionAsync(empId, startDate, scope, companyId). هذا يجلب ArchivedOrders مقسومة على Moderators المرتبطين بهذا المنيجر (من Employees.ManagerId). يُحسَب الـ commission من مجموع هذه الطلبات حسب SalaryMethod (Per Order / Per Item / Commission%). بعد الدفع يُضبَط IsManagerPaid=1 لهذه الطلبات.' },
      { q: 'ماذا يحدث إذا حذفت موظفاً برصيد سالب (سلفة غير مُسدَّدة)؟', a: 'يُحسَب totalDue = CurrentBalance + CarriedOverBalance + AccruedDue. إذا كان سالباً (الموظف يدين الشركة): يُنشأ Debt من نوع Receivable في وحدة الديون. إذا كان إيجابياً (الشركة تدين للموظف): يُنشأ Debt من نوع Payable. يُضبَط IsActive=0 ويُصفَّر CurrentBalance. إذا فشل إنشاء الدين: يُرفَض الحذف حمايةً للرصيد.' },
      { q: 'هل يمكن دفع راتب جزئي؟', a: 'نعم — PayAmount يمكن أن يكون أي قيمة > 0 وأصغر أو يساوي NetDue. الفرق يُحفَظ في CarriedOverBalance ويُضاف تلقائياً للدورة القادمة. لا يمكن دفع أكثر من NetDue (server يرفض) — لكن يمكن دفع أقل بحرية كاملة.' },
      { q: 'هل تُحسَب العمولة على المُرتجَع؟', a: 'يعتمد على CommissionScope. إذا "Delivered Only": تُجلَب فقط الطلبات ذات الحالة Delivered/Partially Delivered — لا عمولة على المُرتجَع. إذا "All Orders": تُجلَب كل الطلبات بغض النظر. هذا الخيار يُحدَّد لكل موظف منفصلاً عند الإضافة.' },
    ],
  },
  related: {
    layout: 'modern',
    title: <>الرواتب لا تعيش بمعزل — <span style={{ color: '#a855f7' }}>تتكامل مع كل المنظومة المالية</span></>,
    items: [
      { to: '/features/expenses', icon: Wallet, title: 'المصروفات والخزينة', body: 'كل دفعة راتب وكل سُلفة تُنشئ تلقائياً مصروفاً (Salaries / Staff Loans) في المصروفات. تؤثر فوراً على رصيد الخزينة وBurn Rate في التقارير المالية.' },
      { to: '/features/debts', icon: ArrowRightLeft, title: 'الديون والمستحقات', body: 'عند حذف موظف برصيد: يُنشأ دين تلقائياً في وحدة الديون. الموظف المدين للشركة → Receivable. الشركة المدينة للموظف → Payable. لا رصيد يختفي بلا سجل.' },
      { to: '/features/reports', icon: FileText, title: 'التقارير المالية', body: 'مصروفات الرواتب والسلف تظهر في تقارير الـ Expense Breakdown. LifetimePaid وMonthPaid يُغذِّيان مؤشرات الكشف المالي الشهري للمقارنة بالإيرادات.' },
      { to: '/features/dashboard', icon: LayoutDashboard, title: 'لوحة القيادة', body: 'DueToday (مستحق الرواتب اليوم) يظهر في لوحة القيادة كمؤشر مالي فوري. أي ارتفاع مفاجئ في الرواتب المستحقة يُعلَم مباشرةً في الـ Dashboard.' },
      { to: '/features/ads', icon: Megaphone, title: 'الإعلانات', body: 'الماركيتر المدفوع بـ Percentage: راتبه = AdSpend × CommissionValue%. تحديث AdSpendInput في HR + تجديد حساب الراتب يعطي تكلفة التسويق الحقيقية شاملةً الموظفين.' },
      { to: '/features/settings', icon: Settings, title: 'الإعدادات والصلاحيات', body: 'موظف HR ≠ مستخدم النظام. صلاحيات الوصول للوحدات والـ RBAC تُدار حصراً من وحدة الإعدادات على AppUser — بدون تداخل مع بيانات الرواتب.' },
    ],
  },
  cta: {
    layout: 'modern',
    icon: Users,
    eyebrow: 'ابدأ الآن',
    title: <>هل تعرف كم يستحق <span style={{ color: '#a855f7' }}>كل موظف لديك اليوم بالضبط؟</span></>,
    description: 'لا إكسيل، لا حسابات يدوية، لا جدالات في نهاية الشهر. عمولات من الطلبات الفعلية، سلف مؤمَّنة بـ DB Locks، رواتب مُعاد حسابها server-side، وقيد محاسبي تلقائي مع كل دفعة. هذا هو مستوى HR الذي يستحقه عملك.',
    primaryLabel: 'ابدأ الآن مجاناً',
    secondaryLabel: 'استعرض الوحدات',
    secondaryToFeatures: true,
    trustBadges: [
      { icon: CheckCircle2, text: 'بدون بطاقة ائتمانية' },
      { icon: CheckCircle2, text: 'إعداد في أقل من ٥ دقائق' },
      { icon: CheckCircle2, text: 'دعم فني كامل بالعربية' },
    ],
  },
}
